# Large Language Models and How to Instruction Tune Them (in a Sustainable Way)

This is an implementation for training and using a Large Language Model (based on [LLaMA](https://ai.meta.com/blog/large-language-model-llama-meta-ai/)) with instructions in order to solve the linguistic tasks. In this lab, we will see how to encode datasets from any format to a sequence to sequence format, train the model using [Q-LoRA](https://arxiv.org/abs/2305.14314), perform the inference using the previous trained model for generating answers to instructions, and finally, how to encode back the data to the original format.. all of it using the only available *T4 GPU with 15GB from Google Colab*.

In [ ]:
# You need to install many libraries!
# PEFT for model parameters efficient finetuning
# SententencePiece for Byte Level Tokenizer
# Accellerate to optimize model over GPU
# bitsandbytes for using quantization!
# datasets for HuggingFace datasets download and processing support
# Moreover you should install the Transformers library (already installed for you on Colab!)

#!pip install -U bitsandbytes
#!pip install peft
#!pip install sentencepiece
#!pip install accelerate
#!pip install datasets
#!pip install -U transformers

# Finetuning data: compare to pretraining and basic preparation

In [ ]:
#!pip install jsonlines
#!pip install datasets

## Look at pretraining data set

In [ ]:
import jsonlines
import itertools
import pandas as pd
from pprint import pprint

import datasets
from datasets import load_dataset
pretraining_dataset = load_dataset(
    "allenai/c4",
    "en",
    split="train",
    streaming=True
)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

README.md: 0.00B [00:00, ?B/s]

Resolving data files:   0%|          | 0/1024 [00:00<?, ?it/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Resolving data files:   0%|          | 0/1024 [00:00<?, ?it/s]

In [ ]:
n = 5
print("Pretrained dataset:")
top_n = itertools.islice(pretraining_dataset, n)
for i in top_n:
  print(i)

Pretrained dataset:
{'text': 'Beginners BBQ Class Taking Place in Missoula!\nDo you want to get better at making delicious BBQ? You will have the opportunity, put this on your calendar now. Thursday, September 22nd join World Class BBQ Champion, Tony Balay from Lonestar Smoke Rangers. He will be teaching a beginner level class for everyone who wants to get better with their culinary skills.\nHe will teach you everything you need to know to compete in a KCBS BBQ competition, including techniques, recipes, timelines, meat selection and trimming, plus smoker and fire information.\nThe cost to be in the class is $35 per person, and for spectators it is free. Included in the cost will be either a t-shirt or apron and you will be tasting samples of each meat that is prepared.', 'timestamp': '2019-04-25 12:57:54', 'url': 'https://klyq.com/beginners-bbq-class-taking-place-in-missoula/'}
{'text': 'Discussion in \'Mac OS X Lion (10.7)\' started by axboi87, Jan 20, 2012.\nI\'ve got a 500gb internal drive and a 240gb SSD.\nWhen trying to restore using disk utility i\'m given the error "Not enough space on disk ____ to restore"\nBut I shouldn\'t have to do that!!!\nAny ideas or workarounds before resorting to the above?\nUse Carbon Copy Cloner to copy one drive to the other. I\'ve done this several times going from larger HDD to smaller SSD and I wound up with a bootable SSD drive. One step you have to remember not to skip is to use Disk Utility to partition the SSD as GUID partition scheme HFS+ before doing the clone. If it came Apple Partition Scheme, even if you let CCC do the clone, the resulting drive won\'t be bootable. CCC usually works in "file mode" and it can easily copy a larger drive (that\'s mostly empty) onto a smaller drive. If you tell CCC to clone a drive you did NOT boot from, it can work in block copy mode where the destination drive must be the same size or larger than the drive you are cloning from (if I recall).\nI\'ve actually done this somehow on Disk Utility several times (booting from a different drive (or even the dvd) so not running disk utility from the drive your cloning) and had it work just fine from larger to smaller bootable clone. Definitely format the drive cloning to first, as bootable Apple etc..\nThanks for pointing this out. My only experience using DU to go larger to smaller was when I was trying to make a Lion install stick and I was unable to restore InstallESD.dmg to a 4 GB USB stick but of course the reason that wouldn\'t fit is there was slightly more than 4 GB of data.', 'timestamp': '2019-04-21 10:07:13', 'url': 'https://forums.macrumors.com/threads/restore-from-larger-disk-to-smaller-disk.1311329/'}
{'text': 'Foil plaid lycra and spandex shortall with metallic slinky insets. Attached metallic elastic belt with O-ring. Headband included. Great hip hop or jazz dance costume. Made in the USA.', 'timestamp': '2019-04-25 10:40:23', 'url': 'https://awishcometrue.com/Catalogs/Clearance/Tweens/V1960-Find-A-Way'}
{'text': "How many backlinks per day for new site?\nDiscussion in 'Black Hat SEO' started by Omoplata, Dec 3, 2010.\n1) for a newly created site, what's the max # backlinks per day I should do to be safe?\n2) how long do I have to let my site age before I can start making more blinks?\nI did about 6000 forum profiles every 24 hours for 10 days for one of my sites which had a brand new domain.\nThere is three backlinks for every of these forum profile so thats 18 000 backlinks every 24 hours and nothing happened in terms of being penalized or sandboxed. This is now maybe 3 months ago and the site is ranking on first page for a lot of my targeted keywords.\nbuild more you can in starting but do manual submission and not spammy type means manual + relevant to the post.. then after 1 month you can make a big blast..\nWow, dude, you built 18k backlinks a day on a brand new site? How quickly did you rank up? What kind of competition/searches did those keywords have?", 'timestamp': '2019-04-21 12:46:19', 'url': 'https://www.blackhatworld.com/seo/how-many-backlinks-per-day-for-new-site.258615/'}
{'text': 'The Denver Board of Education opened the 2017-18 school year with an update on projects that include new construction, upgrades, heat mitigation and quality learning environments.\nWe are excited that Denver students will be the beneficiaries of a four year, $572 million General Obligation Bond. Since the passage of the bond, our construction team has worked to schedule the projects over the four-year term of the bond.\nDenver voters on Tuesday approved bond and mill funding measures for students in Denver Public Schools, agreeing to invest $572 million in bond funding to build and improve schools and $56.6 million in operating dollars to support proven initiatives, such as early literacy.\nDenver voters say yes to bond and mill levy funding support for DPS students and schools. Click to learn more about the details of the voter-approved bond measure.\nDenver voters on Nov. 8 approved bond and mill funding measures for DPS students and schools. Learn more about what’s included in the mill levy measure.', 'timestamp': '2019-04-20 14:33:21', 'url': 'http://bond.dpsk12.org/category/news/'}

You do not need any template for continue the training of the model over plain text! Just follow the standard Auto-Regressive Conditional approach! P(y| y<t)

The only things to add are the **Begin of Sentence \<BOS\>** and the **End of Sentence \<EOS\>** tokens! Be carefull they are Model Specific!

In [ ]:
#Create dataset for continue pre-training.
pretrain_text = []
template_pretrain = "<|begin_of_text|>{text}<|end_of_text|>"

top_n = itertools.islice(pretraining_dataset, 100)
for row in top_n:
  pretrain_text.append(template_pretrain.format(text=row["text"]))

print(pretrain_text[0])

<|begin_of_text|>Beginners BBQ Class Taking Place in Missoula!
Do you want to get better at making delicious BBQ? You will have the opportunity, put this on your calendar now. Thursday, September 22nd join World Class BBQ Champion, Tony Balay from Lonestar Smoke Rangers. He will be teaching a beginner level class for everyone who wants to get better with their culinary skills.
He will teach you everything you need to know to compete in a KCBS BBQ competition, including techniques, recipes, timelines, meat selection and trimming, plus smoker and fire information.
The cost to be in the class is $35 per person, and for spectators it is free. Included in the cost will be either a t-shirt or apron and you will be tasting samples of each meat that is prepared.<|end_of_text|>

## Finetuning dataset format

In [ ]:
instruction_dataset_df = load_dataset("kotzeje/lamini_docs.jsonl", split="train", streaming=True)

n = 5
print("Instruction dataset:")
top_n = itertools.islice(instruction_dataset_df, n)
for i in top_n:
  print(i)

README.md:   0%|          | 0.00/481 [00:00<?, ?B/s]

Instruction dataset:
{'question': 'How can I evaluate the performance and quality of the generated text from Lamini models?', 'answer': "There are several metrics that can be used to evaluate the performance and quality of generated text from Lamini models, including perplexity, BLEU score, and human evaluation. Perplexity measures how well the model predicts the next word in a sequence, while BLEU score measures the similarity between the generated text and a reference text. Human evaluation involves having human judges rate the quality of the generated text based on factors such as coherence, fluency, and relevance. It is recommended to use a combination of these metrics for a comprehensive evaluation of the model's performance."}
{'question': "Can I find information about the code's approach to handling long-running tasks and background jobs?", 'answer': 'Yes, the code includes methods for submitting jobs, checking job status, and retrieving job results. It also includes a method for canceling jobs. Additionally, there is a method for sampling multiple outputs from a model, which could be useful for long-running tasks.'}
{'question': 'How does Lamini AI handle requests for generating text that requires reasoning or decision-making based on given information?', 'answer': 'Lamini AI offers features for generating text that requires logical reasoning or inference beyond simple text generation. It can handle user prompts that involve complex reasoning or logical inference, and can generate text that captures the nuances of different cultural or regional variations.'}
{'question': 'Does the `submit_job()` function expose any advanced training options such as learning rate schedules or early stopping?', 'answer': 'It is unclear which `submit_job()` function is being referred to as there is no such function defined in Lamini’s python library snippets. Please provide more information or context to answer the question accurately.'}
{'question': 'Does the `add_data()` function support different data augmentation techniques or preprocessing options for training data?', 'answer': "No, the `add_data()` function does not support different data augmentation techniques or preprocessing options for training data. It simply adds the provided examples to the program's list of examples."}

## Various ways of formatting your data

In order to use Instructions as a template for a Supervised Fine Tuning Approach, you should use the **appropriate LLM prompt template**, including the answer the model should provide!
[https://github.com/oobabooga/text-generation-webui/tree/main/instruction-templates](https://github.com/oobabooga/text-generation-webui/tree/main/instruction-templates)

In [ ]:
prompt_template_LLaMa = '''<|begin_of_text|><|start_header_id|>system<|end_header_id|>

You are a very helpful assistant. Answer questions as best you can.<|eot_id|><|start_header_id|>user<|end_header_id|>

{question}<|eot_id|><|start_header_id|>assistant<|end_header_id|>

{answer}<|eot_id|><|end_of_text|>'''

In [ ]:
text_with_prompt_template=[]
for row in instruction_dataset_df:
  question = row["question"]
  answer = row["answer"]

  text_with_prompt_template.append(prompt_template_LLaMa.format(question=question, answer=answer))
print(text_with_prompt_template[0])

<|begin_of_text|><|start_header_id|>system<|end_header_id|>

You are a very helpful assistant. Answer questions as best you can.<|eot_id|><|start_header_id|>user<|end_header_id|>

How can I evaluate the performance and quality of the generated text from Lamini models?<|eot_id|><|start_header_id|>assistant<|end_header_id|>

There are several metrics that can be used to evaluate the performance and quality of generated text from Lamini models, including perplexity, BLEU score, and human evaluation. Perplexity measures how well the model predicts the next word in a sequence, while BLEU score measures the similarity between the generated text and a reference text. Human evaluation involves having human judges rate the quality of the generated text based on factors such as coherence, fluency, and relevance. It is recommended to use a combination of these metrics for a comprehensive evaluation of the model's performance.<|eot_id|><|end_of_text|>

The tutorial is split into 4 steps, reflecting the aforementioned process:
- Step 1 - Encoding the data
- **Step 2 - Training the LLaMA model**
- Step 3 - Inference: generating answers
- Step 4 - Evaluate quality of generation

The input of the Notebook is the data we generated previously, in order to train the model.

The "output" will be the trained LLaMA model: we will save it on Google Colab and (optional) upload it to the HuggingFace Hub.

Please make sure you are using the runtime environment according to the following settings: **T4 GPU RUNTIME**

In [ ]:
import warnings
warnings.filterwarnings('ignore')

In [ ]:
import transformers
from transformers import LlamaTokenizer, LlamaForCausalLM
import csv
import json
import torch
from datasets import load_dataset
import pandas as pd

from peft import (
    LoraConfig,
    get_peft_model,
    prepare_model_for_kbit_training,
)

## The Main part
We first load the data that was already prepared to contain maximum 200 examples.

In [ ]:
DEVICE = "cuda"
TOKENIZER_MODEL = "1024m/Llama-3.2-3B-Instruct-Base"
BASE_MODEL = "1024m/Llama-3.2-3B-Instruct-Base"

OUTPUT_DIR = f"HCNLP-Llama-3.2-3B-Instruct-LLamini"

CUTOFF_LEN = 512
CUT_INPUT_CHAR_LENGTH = 1200

In [ ]:
# PREPARE DATA
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained(BASE_MODEL)

from datasets import Dataset
def tokenize(prompt):
    print(prompt["text"])
    result = tokenizer(
        prompt["text"],
        truncation=True,
        max_length=512,
        padding=False,
        return_tensors=None,
    )
    if (
        result["input_ids"][-1] != tokenizer.eos_token_id
        and len(result["input_ids"]) < 512
    ):
        result["input_ids"].append(tokenizer.eos_token_id)
        result["attention_mask"].append(1)

    result["labels"] = result["input_ids"].copy()
    return result


def gen():
  for t in text_with_prompt_template[:200]:
    yield {"text":t}

train_data = Dataset.from_generator(gen)
train_data = train_data.map(tokenize)


def gen2():
  for t in text_with_prompt_template[200:400]:
    yield {"text":t}

validation_data = Dataset.from_generator(gen2)
validation_data = validation_data.map(tokenize)

Generating train split: 0 examples [00:00, ? examples/s]

Map:   0%|          | 0/200 [00:00<?, ? examples/s]

<|begin_of_text|><|start_header_id|>system<|end_header_id|>

You are a very helpful assistant. Answer questions as best you can.<|eot_id|><|start_header_id|>user<|end_header_id|>

How can I evaluate the performance and quality of the generated text from Lamini models?<|eot_id|><|start_header_id|>assistant<|end_header_id|>

There are several metrics that can be used to evaluate the performance and quality of generated text from Lamini models, including perplexity, BLEU score, and human evaluation. Perplexity measures how well the model predicts the next word in a sequence, while BLEU score measures the similarity between the generated text and a reference text. Human evaluation involves having human judges rate the quality of the generated text based on factors such as coherence, fluency, and relevance. It is recommended to use a combination of these metrics for a comprehensive evaluation of the model's performance.<|eot_id|><|end_of_text|>
<|begin_of_text|><|start_header_id|>system<|end_header_id|>

You are a very helpful assistant. Answer questions as best you can.<|eot_id|><|start_header_id|>user<|end_header_id|>

Can I find information about the code's approach to handling long-running tasks and background jobs?<|eot_id|><|start_header_id|>assistant<|end_header_id|>

Yes, the code includes methods for submitting jobs, checking job status, and retrieving job results. It also includes a method for canceling jobs. Additionally, there is a method for sampling multiple outputs from a model, which could be useful for long-running tasks.<|eot_id|><|end_of_text|>
<|begin_of_text|><|start_header_id|>system<|end_header_id|>

You are a very helpful assistant. Answer questions as best you can.<|eot_id|><|start_header_id|>user<|end_header_id|>

How does Lamini AI handle requests for generating text that requires reasoning or decision-making based on given information?<|eot_id|><|start_header_id|>assistant<|end_header_id|>

Lamini AI offers features for generating text that requires logical reasoning or inference beyond simple text generation. It can handle user prompts that involve complex reasoning or logical inference, and can generate text that captures the nuances of different cultural or regional variations.<|eot_id|><|end_of_text|>
<|begin_of_text|><|start_header_id|>system<|end_header_id|>

You are a very helpful assistant. Answer questions as best you can.<|eot_id|><|start_header_id|>user<|end_header_id|>

Does the `submit_job()` function expose any advanced training options such as learning rate schedules or early stopping?<|eot_id|><|start_header_id|>assistant<|end_header_id|>

It is unclear which `submit_job()` function is being referred to as there is no such function defined in Lamini’s python library snippets. Please provide more information or context to answer the question accurately.<|eot_id|><|end_of_text|>
<|begin_of_text|><|start_header_id|>system<|end_header_id|>

You are a very helpful assistant. Answer questions as best you can.<|eot_id|><|start_header_id|>user<|end_header_id|>

Does the `add_data()` function support different data augmentation techniques or preprocessing options for training data?<|eot_id|><|start_header_id|>assistant<|end_header_id|>

No, the `add_data()` function does not support different data augmentation techniques or preprocessing options for training data. It simply adds the provided examples to the program's list of examples.<|eot_id|><|end_of_text|>
<|begin_of_text|><|start_header_id|>system<|end_header_id|>

You are a very helpful assistant. Answer questions as best you can.<|eot_id|><|start_header_id|>user<|end_header_id|>

Can Lamini generate text for data storytelling or data visualization purposes?<|eot_id|><|start_header_id|>assistant<|end_header_id|>

Yes, Lamini can generate text for data storytelling or data visualization purposes using its natural language generation capabilities.<|eot_id|><|end_of_text|>
<|begin_of_text|><|start_header_id|>system<|end_header_id|>

You are a very helpful assistant. Answer questions as best you can.<|eot_id|><|start_header_id|>user<|end_header_id|>

Can the documentation predict the outcome of a coin toss?<|eot_id|><|start_header_id|>assistant<|end_header_id|>

I wish! This documentation only talks about Lamini’s LLM Engine.<|eot_id|><|end_of_text|>
<|begin_of_text|><|start_header_id|>system<|end_header_id|>

You are a very helpful assistant. Answer questions as best you can.<|eot_id|><|start_header_id|>user<|end_header_id|>

How does the `submit_job()` function work in Lamini? What does it mean to submit a job, and what happens behind the scenes?<|eot_id|><|start_header_id|>assistant<|end_header_id|>

The `submit_job()` function in Lamini is used to submit a job for training a machine learning model. When you submit a job, Lamini takes the training data and uses it to train a model based on the specified parameters. Behind the scenes, Lamini uses distributed computing to train the model on multiple machines, which allows for faster training times. Once the training is complete, the resulting model is saved and can be used for inference.<|eot_id|><|end_of_text|>
<|begin_of_text|><|start_header_id|>system<|end_header_id|>

You are a very helpful assistant. Answer questions as best you can.<|eot_id|><|start_header_id|>user<|end_header_id|>

Does Lamini support generating code<|eot_id|><|start_header_id|>assistant<|end_header_id|>

Yes, Lamini supports generating code through its API.<|eot_id|><|end_of_text|>
<|begin_of_text|><|start_header_id|>system<|end_header_id|>

You are a very helpful assistant. Answer questions as best you can.<|eot_id|><|start_header_id|>user<|end_header_id|>

Can Lamini be used to create chatbots or virtual assistants?<|eot_id|><|start_header_id|>assistant<|end_header_id|>

Yes, Lamini can be used to build conversational AI agents or chatbots. It provides tools and functionalities for generating coherent and contextually appropriate responses in conversational settings, as well as support for multi-turn conversations and context-aware recommendation systems.<|eot_id|><|end_of_text|>
<|begin_of_text|><|start_header_id|>system<|end_header_id|>

You are a very helpful assistant. Answer questions as best you can.<|eot_id|><|start_header_id|>user<|end_header_id|>

How can Lamini be used to generate text with specific stylistic attributes, such as poetic language or persuasive rhetoric?<|eot_id|><|start_header_id|>assistant<|end_header_id|>

Lamini can be trained to generate text with specific stylistic attributes by fine-tuning its language model on a dataset that includes examples of the desired style. For example, to generate text with poetic language, the model can be trained on a corpus of poetry. Similarly, to generate text with persuasive rhetoric, the model can be trained on a dataset of persuasive speeches or advertisements. By adjusting the training data and fine-tuning the model, Lamini can be customized to generate text with a wide range of stylistic attributes.<|eot_id|><|end_of_text|>
<|begin_of_text|><|start_header_id|>system<|end_header_id|>

You are a very helpful assistant. Answer questions as best you can.<|eot_id|><|start_header_id|>user<|end_header_id|>

Is it possible to fine-tune Lamini on a small dataset with limited annotations?<|eot_id|><|start_header_id|>assistant<|end_header_id|>

Yes, it is possible to fine-tune Lamini on a small dataset with limited annotations using the DatasetBalancer class in the balancer.py file. The stochastic_balance_dataset and full_balance_dataset methods can be used to balance the dataset with embeddings and improve the performance of the model.<|eot_id|><|end_of_text|>
<|begin_of_text|><|start_header_id|>system<|end_header_id|>

You are a very helpful assistant. Answer questions as best you can.<|eot_id|><|start_header_id|>user<|end_header_id|>

How can I handle long texts or documents when using Lamini? Are there any limitations or considerations?<|eot_id|><|start_header_id|>assistant<|end_header_id|>

Lamini can handle long or complex documents during the training process, but there may be limitations or considerations depending on the available computational resources and the specific task or model architecture. It is recommended to preprocess the input data and split it into smaller chunks or batches to improve efficiency and avoid memory issues. Additionally, it may be necessary to adjust the hyperparameters or use specialized techniques such as hierarchical or attention-based models to handle long sequences effectively. The Lamini documentation provides guidelines and best practices for handling long texts or documents, and it is recommended to consult it for more information.<|eot_id|><|end_of_text|>
<|begin_of_text|><|start_header_id|>system<|end_header_id|>

You are a very helpful assistant. Answer questions as best you can.<|eot_id|><|start_header_id|>user<|end_header_id|>

How do I report a bug or issue with the Lamini documentation?<|eot_id|><|start_header_id|>assistant<|end_header_id|>

You can report a bug or issue with the Lamini documentation by submitting an issue on the Lamini GitHub page.<|eot_id|><|end_of_text|>
<|begin_of_text|><|start_header_id|>system<|end_header_id|>

You are a very helpful assistant. Answer questions as best you can.<|eot_id|><|start_header_id|>user<|end_header_id|>

Can Lamini be used in an online learning setting, where the model is updated continuously as new data becomes available?<|eot_id|><|start_header_id|>assistant<|end_header_id|>

It is possible to use Lamini in an online learning setting where the model is updated continuously as new data becomes available. However, this would require some additional implementation and configuration to ensure that the model is updated appropriately and efficiently.<|eot_id|><|end_of_text|>
<|begin_of_text|><|start_header_id|>system<|end_header_id|>

You are a very helpful assistant. Answer questions as best you can.<|eot_id|><|start_header_id|>user<|end_header_id|>

What is the company culture that Lamini AI values?<|eot_id|><|start_header_id|>assistant<|end_header_id|>

Lamini AI believes in the following:\n1. Innovation and Creativity: Lamini AI values a culture of innovation and encourages employees to think creatively, explore new ideas, and push the boundaries of AI technology. This includes fostering an environment that supports experimentation, welcomes novel approaches, and rewards innovative solutions.\n2. Collaboration and Teamwork: Collaboration is essential in AI development. Lamini AI values a culture that promotes teamwork, open communication, and knowledge sharing. Employees are encouraged to collaborate across teams, departments, and disciplines to leverage collective expertise and achieve common goals.\n3. Continuous Learning and Growth: Given the dynamic nature of AI, Lamini AI promotes a culture of continuous learning and growth. Employees are encouraged to expand their knowledge, stay updated with the latest AI advancements, and pursue professional development opportunities. This may include providing resources for training, attending conferences, and fostering a culture of intellectual curiosity.\n4. Diversity and Inclusion: Building a diverse and inclusive workforce is a priority for Lamini AI, which values diversity in its team, recognizing the importance of different perspectives, backgrounds, and experiences in driving innovation and creativity. The company fostes an inclusive culture that promotes equality, respect, and opportunities for all employees.\n5. Customer-Centric Approach: Lamini AI is focused on providing value to its customers. The company has a customer-centric culture that emphasizes understanding customer needs, delivering exceptional user experiences, and providing prompt and effective support. Customer feedback and satisfaction plays a vital role in shaping the company's products and services.<|eot_id|><|end_of_text|>
<|begin_of_text|><|start_header_id|>system<|end_header_id|>

You are a very helpful assistant. Answer questions as best you can.<|eot_id|><|start_header_id|>user<|end_header_id|>

Can Lamini generate text that simulates a particular persona or writing style, such as mimicking famous authors or historical figures?<|eot_id|><|start_header_id|>assistant<|end_header_id|>

Yes, Lamini has the capability to generate text that emulates the style of famous authors or literary figures, as well as mimicking the writing style of a specific time period, such as the Victorian era or the Renaissance. This can be achieved through fine-tuning Lamini's language models with specific training data and prompts that reflect the desired persona or writing style. However, it is important to note that the quality and accuracy of the generated text may vary depending on the complexity and specificity of the desired persona or style.<|eot_id|><|end_of_text|>
<|begin_of_text|><|start_header_id|>system<|end_header_id|>

You are a very helpful assistant. Answer questions as best you can.<|eot_id|><|start_header_id|>user<|end_header_id|>

What is Lamini and what is its collaboration with Databricks about?<|eot_id|><|start_header_id|>assistant<|end_header_id|>

Lamini is a library that simplifies the process of accessing data in Databricks. The collaboration between Lamini and Databricks involves integrating Lamini with the Databricks platform to provide a seamless experience for users.<|eot_id|><|end_of_text|>
<|begin_of_text|><|start_header_id|>system<|end_header_id|>

You are a very helpful assistant. Answer questions as best you can.<|eot_id|><|start_header_id|>user<|end_header_id|>

Are you prompt-engineered?<|eot_id|><|start_header_id|>assistant<|end_header_id|>

Sorry I can't reveal that information to you. I am trained by the amazing team at Lamini, to know more contact them<|eot_id|><|end_of_text|>
<|begin_of_text|><|start_header_id|>system<|end_header_id|>

You are a very helpful assistant. Answer questions as best you can.<|eot_id|><|start_header_id|>user<|end_header_id|>

 <|eot_id|><|start_header_id|>assistant<|end_header_id|>

Did you type something, I am having trouble understanding<|eot_id|><|end_of_text|>
<|begin_of_text|><|start_header_id|>system<|end_header_id|>

You are a very helpful assistant. Answer questions as best you can.<|eot_id|><|start_header_id|>user<|end_header_id|>

Can Lamini generate code snippets or programming examples for different programming languages?<|eot_id|><|start_header_id|>assistant<|end_header_id|>

Yes, Lamini can generate code snippets and provide programming assistance for specific languages during the customization process of a language model.<|eot_id|><|end_of_text|>
<|begin_of_text|><|start_header_id|>system<|end_header_id|>

You are a very helpful assistant. Answer questions as best you can.<|eot_id|><|start_header_id|>user<|end_header_id|>

Are there any tutorials on using Lamini for content generation in storytelling games?<|eot_id|><|start_header_id|>assistant<|end_header_id|>

Lamini has many tutorials and examples of how to use its LLM Engine available in its documentation, which you can find online through lamini.ai. You can easily adapt those instructions to any application involving an LLM that you see fit!<|eot_id|><|end_of_text|>
<|begin_of_text|><|start_header_id|>system<|end_header_id|>

You are a very helpful assistant. Answer questions as best you can.<|eot_id|><|start_header_id|>user<|end_header_id|>

Does Lamini require an internet connection to function?<|eot_id|><|start_header_id|>assistant<|end_header_id|>

Yes, Lamini requires an internet connection to function as it is a cloud-based AI language model.<|eot_id|><|end_of_text|>
<|begin_of_text|><|start_header_id|>system<|end_header_id|>

You are a very helpful assistant. Answer questions as best you can.<|eot_id|><|start_header_id|>user<|end_header_id|>

Can you explain the CC-BY license mentioned? What does it allow me to do with the customized language model?<|eot_id|><|start_header_id|>assistant<|end_header_id|>

Lamini allows for commercial use of their LLM technology under a permissive Apache 2.0 license unless otherwise specified. You keep access and ownership of your own data, and we don’t use your data to train models for anyone else but you. For more information, please reach out to Lamini directly.<|eot_id|><|end_of_text|>
<|begin_of_text|><|start_header_id|>system<|end_header_id|>

You are a very helpful assistant. Answer questions as best you can.<|eot_id|><|start_header_id|>user<|end_header_id|>

What are the benefits of using the Lamini data generator for LLM training?<|eot_id|><|start_header_id|>assistant<|end_header_id|>

The benefits of using the Lamini data generator for LLM training include the ability to generate high-quality, diverse datasets that can improve the performance and accuracy of language models. The data generator can also be customized for specific use cases or vertical-specific languages, and can handle data preprocessing tasks such as tokenization and data cleaning. Additionally, the generated dataset is available for commercial use, and the data generator pipeline can be optimized to reduce performance plateaus and improve training efficiency.<|eot_id|><|end_of_text|>
<|begin_of_text|><|start_header_id|>system<|end_header_id|>

You are a very helpful assistant. Answer questions as best you can.<|eot_id|><|start_header_id|>user<|end_header_id|>

Are there any success stories or case studies showcasing how Lamini has been used by other enterprise organizations?<|eot_id|><|start_header_id|>assistant<|end_header_id|>

Yes, there are several success stories and case studies showcasing how Lamini has been used by other enterprise organizations. For example, Lamini has been used by companies in the financial industry to generate financial reports and by healthcare organizations to generate medical reports. Lamini has also been used by e-commerce companies to generate product descriptions and by social media companies to generate captions for images. These success stories demonstrate the versatility and effectiveness of Lamini in various industries and use cases.<|eot_id|><|end_of_text|>
<|begin_of_text|><|start_header_id|>system<|end_header_id|>

You are a very helpful assistant. Answer questions as best you can.<|eot_id|><|start_header_id|>user<|end_header_id|>

Can Lamini be used for multiple languages, or is it primarily focused on English?<|eot_id|><|start_header_id|>assistant<|end_header_id|>

LLM Engine Lamini can be used for multiple languages, not just English.<|eot_id|><|end_of_text|>
<|begin_of_text|><|start_header_id|>system<|end_header_id|>

You are a very helpful assistant. Answer questions as best you can.<|eot_id|><|start_header_id|>user<|end_header_id|>

Are there any known challenges or trade-offs associated with using Lamini for model customization tasks?<|eot_id|><|start_header_id|>assistant<|end_header_id|>


Generating train split: 0 examples [00:00, ? examples/s]

Map:   0%|          | 0/200 [00:00<?, ? examples/s]

<|begin_of_text|><|start_header_id|>system<|end_header_id|>

You are a very helpful assistant. Answer questions as best you can.<|eot_id|><|start_header_id|>user<|end_header_id|>

Can Lamini generate human-readable explanations for the predictions made by a customized LLM?<|eot_id|><|start_header_id|>assistant<|end_header_id|>

Yes, Lamini can generate human-readable explanations for the predictions made by a customized LLM. Lamini provides a feature called "Explainability" which allows users to understand how the model arrived at a particular prediction. This feature generates explanations in natural language, making it easy for users to understand the reasoning behind the model's predictions.<|eot_id|><|end_of_text|>
<|begin_of_text|><|start_header_id|>system<|end_header_id|>

You are a very helpful assistant. Answer questions as best you can.<|eot_id|><|start_header_id|>user<|end_header_id|>

Is it possible to fine-tune Lamini on a specific dataset for dialogue generation?<|eot_id|><|start_header_id|>assistant<|end_header_id|>

Yes, it is possible to fine-tune Lamini on a specific dataset for dialogue generation. The LLM Engine class in Lamini’s python library allows for adding data to the model, which can be used to fine-tune it on a specific dataset. Additionally, the add_model method can be used to create multiple models with different parameters and output types.<|eot_id|><|end_of_text|>
<|begin_of_text|><|start_header_id|>system<|end_header_id|>

You are a very helpful assistant. Answer questions as best you can.<|eot_id|><|start_header_id|>user<|end_header_id|>

Are there any specific guidelines or recommendations in the Lamini library documentation for optimizing the memory usage during model inference?<|eot_id|><|start_header_id|>assistant<|end_header_id|>

Yes, the Lamini library documentation provides some guidelines for optimizing memory usage during model inference. One recommendation is to use the `llm.add_data()` method to load data in batches rather than all at once, which can help reduce memory usage. Additionally, the documentation suggests using smaller batch sizes and reducing the maximum sequence length to further optimize memory usage.<|eot_id|><|end_of_text|>
<|begin_of_text|><|start_header_id|>system<|end_header_id|>

You are a very helpful assistant. Answer questions as best you can.<|eot_id|><|start_header_id|>user<|end_header_id|>

Can Lamini be used for generating text for social media posts or microblogging platforms?<|eot_id|><|start_header_id|>assistant<|end_header_id|>

Yes, Lamini can be used for generating text for social media posts or microblogging platforms. With its natural language generation capabilities, Lamini can generate short and concise text that is suitable for these platforms. However, it is important to ensure that the generated text is relevant and engaging for the target audience.<|eot_id|><|end_of_text|>
<|begin_of_text|><|start_header_id|>system<|end_header_id|>

You are a very helpful assistant. Answer questions as best you can.<|eot_id|><|start_header_id|>user<|end_header_id|>

Can you get a tan through a window?<|eot_id|><|start_header_id|>assistant<|end_header_id|>

Let’s keep the discussion relevant to Lamini.<|eot_id|><|end_of_text|>
<|begin_of_text|><|start_header_id|>system<|end_header_id|>

You are a very helpful assistant. Answer questions as best you can.<|eot_id|><|start_header_id|>user<|end_header_id|>

How does Lamini handle generating text that includes proper nouns or specific entities mentioned in the input?<|eot_id|><|start_header_id|>assistant<|end_header_id|>

Lamini can handle generating text that includes proper nouns or specific entities mentioned in the input by using named entity recognition (NER) techniques. NER allows Lamini to identify and extract named entities such as people, organizations, and locations from the input text, and then incorporate them into the generated output in a contextually appropriate manner. This can help to improve the coherence and relevance of the generated text, particularly in domains where specific entities or terminology are important.<|eot_id|><|end_of_text|>
<|begin_of_text|><|start_header_id|>system<|end_header_id|>

You are a very helpful assistant. Answer questions as best you can.<|eot_id|><|start_header_id|>user<|end_header_id|>

What are the latency and response time considerations when using Lamini's text generation capabilities in real-time applications?<|eot_id|><|start_header_id|>assistant<|end_header_id|>

When using Lamini's text generation capabilities in real-time applications, it is important to consider the latency and response time. The speed of the response will depend on factors such as the complexity of the text generation task, the size of the input data, and the computational resources available. To ensure optimal performance, it may be necessary to optimize the Lamini model and infrastructure, as well as implement caching and other performance-enhancing techniques. Additionally, it is important to monitor and analyze the response times to identify and address any bottlenecks or issues that may arise.<|eot_id|><|end_of_text|>
<|begin_of_text|><|start_header_id|>system<|end_header_id|>

You are a very helpful assistant. Answer questions as best you can.<|eot_id|><|start_header_id|>user<|end_header_id|>

Can you elaborate on the process of fine-tuning the hyperparameters in Lamini? Are there any guidelines or recommendations for selecting optimal settings?<|eot_id|><|start_header_id|>assistant<|end_header_id|>

In Lamini, the process of fine-tuning hyperparameters is handled automatically based on the specific use case. Rather than requiring manual intervention, Lamini employs intelligent algorithms and optimization techniques to automatically set the hyperparameters of the model. This process involves exploring the hyperparameter space and evaluating different combinations of values to find the optimal settings. Lamini leverages its computational resources efficiently to run multiple model instances in parallel or sequentially, comparing their performance to identify the best configuration. While Lamini does not rely on specific guidelines or recommendations for hyperparameter selection, it uses advanced techniques like grid search, random search, Bayesian optimization, or genetic algorithms to navigate the hyperparameter space effectively and find the settings that maximize the model's performance for the given use case.<|eot_id|><|end_of_text|>
<|begin_of_text|><|start_header_id|>system<|end_header_id|>

You are a very helpful assistant. Answer questions as best you can.<|eot_id|><|start_header_id|>user<|end_header_id|>

Are there any regularization techniques or hyperparameter tuning options available in Lamini?<|eot_id|><|start_header_id|>assistant<|end_header_id|>

Yes, Lamini provides several regularization techniques such as dropout, weight decay, and early stopping to prevent overfitting during the training process. Additionally, users can tune hyperparameters such as learning rate, batch size, and number of epochs to optimize the performance of their customized language models.<|eot_id|><|end_of_text|>
<|begin_of_text|><|start_header_id|>system<|end_header_id|>

You are a very helpful assistant. Answer questions as best you can.<|eot_id|><|start_header_id|>user<|end_header_id|>

Can the `improve()` function be used iteratively to fine-tune the model multiple times on the same dataset?<|eot_id|><|start_header_id|>assistant<|end_header_id|>

Yes, the `improve()` function can be used iteratively to fine-tune the model multiple times on the same dataset. This can be done by calling the `improve()` function multiple times with the same dataset, which will update the model's parameters each time and improve its performance.<|eot_id|><|end_of_text|>
<|begin_of_text|><|start_header_id|>system<|end_header_id|>

You are a very helpful assistant. Answer questions as best you can.<|eot_id|><|start_header_id|>user<|end_header_id|>

Can Lamini generate text that is optimized for specific reading levels, such as elementary or advanced?<|eot_id|><|start_header_id|>assistant<|end_header_id|>

Yes, Lamini has the capability to generate text that is optimized for specific reading levels, including elementary and advanced levels. This can be achieved through fine-tuning the language model on specific datasets or by adjusting the complexity of the generated text through various parameters.<|eot_id|><|end_of_text|>
<|begin_of_text|><|start_header_id|>system<|end_header_id|>

You are a very helpful assistant. Answer questions as best you can.<|eot_id|><|start_header_id|>user<|end_header_id|>

How do I add my data to Lamini's interface<|eot_id|><|start_header_id|>assistant<|end_header_id|>

You can quickly add data to Lamini’s interface using LLM Engine.add_data. This method allows you to make data available to the model for inference and training.<|eot_id|><|end_of_text|>
<|begin_of_text|><|start_header_id|>system<|end_header_id|>

You are a very helpful assistant. Answer questions as best you can.<|eot_id|><|start_header_id|>user<|end_header_id|>

Can you provide any real-life examples of how Lamini has been used to improve language models in different industries or fields?<|eot_id|><|start_header_id|>assistant<|end_header_id|>

Check out the Lamini website for examples and walkthroughs. With some imagination, you can adapt those examples to your data and use case. LLMs can be used anywhere large volumes of text data exist and are processed.<|eot_id|><|end_of_text|>
<|begin_of_text|><|start_header_id|>system<|end_header_id|>

You are a very helpful assistant. Answer questions as best you can.<|eot_id|><|start_header_id|>user<|end_header_id|>

Does Lamini support multiple programming languages or frameworks?<|eot_id|><|start_header_id|>assistant<|end_header_id|>

Yes, Lamini supports multiple programming languages and frameworks. It can be used with Python, Java, JavaScript, and other popular programming languages. Additionally, it can be integrated with popular machine learning frameworks such as TensorFlow and PyTorch.<|eot_id|><|end_of_text|>
<|begin_of_text|><|start_header_id|>system<|end_header_id|>

You are a very helpful assistant. Answer questions as best you can.<|eot_id|><|start_header_id|>user<|end_header_id|>

Can Lamini AI assist in generating text for chatbot applications or virtual assistants?<|eot_id|><|start_header_id|>assistant<|end_header_id|>

Yes, Lamini AI can assist in generating text for chatbot applications or virtual assistants. It offers features for generating text with specific rhetorical devices, domain-specific technical knowledge, cultural or regional context, different writing styles, and a specific level of readability or complexity.<|eot_id|><|end_of_text|>
<|begin_of_text|><|start_header_id|>system<|end_header_id|>

You are a very helpful assistant. Answer questions as best you can.<|eot_id|><|start_header_id|>user<|end_header_id|>

How do I run the LLM engine in the Lamini Python package?<|eot_id|><|start_header_id|>assistant<|end_header_id|>

You can run the LLM engine in the Lamini Python package by importing the LLM engine (called llama) in your python interpreter and then creating a Type class for data and a Context class for attributes. You can then instantiate the LLM engine and add data to it. Finally, you can run the LLM engine with a basic test to see if installation and authentication were set up correctly.<|eot_id|><|end_of_text|>
<|begin_of_text|><|start_header_id|>system<|end_header_id|>

You are a very helpful assistant. Answer questions as best you can.<|eot_id|><|start_header_id|>user<|end_header_id|>

How does Lamini AI compare to other LLM engines available in the market?<|eot_id|><|start_header_id|>assistant<|end_header_id|>

Lamini AI is a leading LLM engine that offers a wide range of features and capabilities for training and deploying custom LLM models. It is optimized for speed and accuracy, and can handle large and complex datasets. It also offers enterprise features such as virtual private cloud (VPC) deployments, and can be integrated with existing infrastructure and tools. Lamini AI also provides support and assistance for developers using their platform and library. Compared to other LLM engines, Lamini AI offers a comprehensive set of features and capabilities that make it a great choice for both small-scale projects and large-scale enterprise deployments.<|eot_id|><|end_of_text|>
<|begin_of_text|><|start_header_id|>system<|end_header_id|>

You are a very helpful assistant. Answer questions as best you can.<|eot_id|><|start_header_id|>user<|end_header_id|>

Are there any plans for further integration or collaboration between Lamini and LlamaIndex in the future?<|eot_id|><|start_header_id|>assistant<|end_header_id|>

Future integration or collaboration plans between Lamini and LlamaIndex could involve further enhancements to streamline the process of customizing LLMs and connecting them with external data. This could include improved documentation, additional features, or deeper integration between the two projects to provide a more cohesive experience for developers.<|eot_id|><|end_of_text|>
<|begin_of_text|><|start_header_id|>system<|end_header_id|>

You are a very helpful assistant. Answer questions as best you can.<|eot_id|><|start_header_id|>user<|end_header_id|>

Can Lamini be used on a regular computer, or do I need specialized hardware or software?<|eot_id|><|start_header_id|>assistant<|end_header_id|>

Lamini can be used on a regular computer without any specialized hardware or software by using the python client or REST APIs. It is designed to be easily accessible and user-friendly.  The LLM Engine itself requires GPU accelerated servers capable of running large language models.  Lamini hosts such machines that can be easily connected to, e.g. from a jupyter notebook or python program.  Lamini also offers enterprise deployments of the LLM Engine on your infrastructure.<|eot_id|><|end_of_text|>
<|begin_of_text|><|start_header_id|>system<|end_header_id|>

You are a very helpful assistant. Answer questions as best you can.<|eot_id|><|start_header_id|>user<|end_header_id|>

Does the Lamini library provide any SDKs or libraries to simplify the integration of Lamini into my software project?<|eot_id|><|start_header_id|>assistant<|end_header_id|>

Yes, the Lamini library provides SDKs and libraries for various programming languages, including Python, Java, and JavaScript, to simplify the integration of Lamini into your software project. These SDKs and libraries offer pre-built functions and methods for common tasks, such as model initialization, inference, and result processing, making it easier to incorporate Lamini into your existing codebase. Additionally, the Lamini documentation provides detailed instructions and examples on how to use these SDKs and libraries, as well as best practices for integrating Lamini into your software project.<|eot_id|><|end_of_text|>
<|begin_of_text|><|start_header_id|>system<|end_header_id|>

You are a very helpful assistant. Answer questions as best you can.<|eot_id|><|start_header_id|>user<|end_header_id|>

Can Lamini assist in generating content for social media marketing campaigns?<|eot_id|><|start_header_id|>assistant<|end_header_id|>

Lamini is a language model engine that can generate any type of content. We have a Tweet example in our documentation. The code includes a class for a "Tweet" type and a "User" type, and a function to retrieve tweet data. The code also includes methods to improve the generated tweets by increasing likes and retweets, and removing hashtags. Therefore, it is possible that Lamini can assist in generating content for social media marketing campaigns.<|eot_id|><|end_of_text|>
<|begin_of_text|><|start_header_id|>system<|end_header_id|>

You are a very helpful assistant. Answer questions as best you can.<|eot_id|><|start_header_id|>user<|end_header_id|>

Can animals laugh?<|eot_id|><|start_header_id|>assistant<|end_header_id|>

Let’s keep the discussion relevant to Lamini.<|eot_id|><|end_of_text|>
<|begin_of_text|><|start_header_id|>system<|end_header_id|>

You are a very helpful assistant. Answer questions as best you can.<|eot_id|><|start_header_id|>user<|end_header_id|>

Does Lamini have a limit on the number of API requests I can make?<|eot_id|><|start_header_id|>assistant<|end_header_id|>

Lamini provides each user with free tokens up front.<|eot_id|><|end_of_text|>
<|begin_of_text|><|start_header_id|>system<|end_header_id|>

You are a very helpful assistant. Answer questions as best you can.<|eot_id|><|start_header_id|>user<|end_header_id|>

Can I access previous versions of the documentation for reference?<|eot_id|><|start_header_id|>assistant<|end_header_id|>

Only the latest version of our documentation is available at https://lamini-ai.github.io/. Stay tuned for updates!<|eot_id|><|end_of_text|>
<|begin_of_text|><|start_header_id|>system<|end_header_id|>

You are a very helpful assistant. Answer questions as best you can.<|eot_id|><|start_header_id|>user<|end_header_id|>

Does Lamini support distributed training across multiple machines or GPUs?<|eot_id|><|start_header_id|>assistant<|end_header_id|>

Yes, Lamini supports distributed training across multiple machines or GPUs. This allows for faster and more efficient training of large language models. Lamini uses the Horovod framework for distributed training, which enables scaling to hundreds or thousands of GPUs.<|eot_id|><|end_of_text|>
<|begin_of_text|><|start_header_id|>system<|end_header_id|>

You are a very helpful assistant. Answer questions as best you can.<|eot_id|><|start_header_id|>user<|end_header_id|>

In the `get_job_result()` function, what type of output can we expect? Does it provide model weights, predictions, or evaluation metrics?<|eot_id|><|start_header_id|>assistant<|end_header_id|>

The `get_job_result()` function provides the final results of batch inference jobs, meaning it returns all the results of the job to the user as an array of output values.<|eot_id|><|end_of_text|>
<|begin_of_text|><|start_header_id|>system<|end_header_id|>

You are a very helpful assistant. Answer questions as best you can.<|eot_id|><|start_header_id|>user<|end_header_id|>

Can Lamini generate text that adheres to specific guidelines or requirements, such as word counts or specific topics?<|eot_id|><|start_header_id|>assistant<|end_header_id|>

Yes, Lamini can generate text that adheres to specific guidelines or requirements such as word counts or specific topics. This can be achieved by providing prompts or seed text that guide the model towards the desired output. Additionally, Lamini allows for the use of various parameters such as `length_penalty` and `repetition_penalty` to control the length and repetition of generated text. With proper fine-tuning and training, Lamini can generate text that meets specific requirements and guidelines.<|eot_id|><|end_of_text|>
<|begin_of_text|><|start_header_id|>system<|end_header_id|>

You are a very helpful assistant. Answer questions as best you can.<|eot_id|><|start_header_id|>user<|end_header_id|>

Are there any limitations on the size of input data that Lamini can handle?<|eot_id|><|start_header_id|>assistant<|end_header_id|>

There are no limitations on the size of input data or supporting data that Lamini can handle. Please reach out to Lamini’s team if you have any further questions about data, or if you have high traffic use cases you’d like to explore. Lamini can help scale out any language model for production.<|eot_id|><|end_of_text|>
<|begin_of_text|><|start_header_id|>system<|end_header_id|>

You are a very helpful assistant. Answer questions as best you can.<|eot_id|><|start_header_id|>user<|end_header_id|>

How should the data be formatted in order to send it to Lamini<|eot_id|><|start_header_id|>assistant<|end_header_id|>


In [ ]:
train_data

Dataset({
    features: ['text', 'input_ids', 'attention_mask', 'labels'],
    num_rows: 200
})

In [ ]:
validation_data

Dataset({
    features: ['text', 'input_ids', 'attention_mask', 'labels'],
    num_rows: 200
})

------------------------------
## Hyper-parameteres

Here we set all the hyper-parameters we need:
- specify the device to exploit the GPU (`cuda`)
- use the tokenizer for llama
- we set then the LoRA hyper-params:
  - the rank `R` of the two matrices A and B
  - the normalization factor `Alpha`
  - the `dropout rate`
  - the target modules, i.e. where to insert the LoRA modules: `q`, `k` and `v` for the attention and `o` for the final output layer.
- `number of epochs` to train the model
- `batch_size` is the global size of our batch of examples, but since we have a small GPU with only 15GB of memory, we need to scale this down, so we introduce 2 new concepts:
  - `micro_batch_size` is the real size of the batch we will use, which will be smaller (usually 2,4,8)
  - `gradient_accumulation_steps` how many steps (of batches) we want to accumulate the `loss` for before we update the parameters of the model. In this way we simulate a bigger `batch_size` by accumulating the `loss` for more than one iteration, and then we update the model.
- the `learning_rate`, which controls the intensity of the update
- the `warmup_ratio`, as we are using a scheduler for the learning rate, i.e. it will not be fixed during the whole training, but will vary based on the time.

We will be using a linear decay scheduler with warmup of `0.1`, as in the figure below. This means it will linearly grow for `10%` of the training, and the linearly decay for the rest.

<img src="https://i.stack.imgur.com/Ujhvo.png" width="450px">

In [ ]:

LORA_R = 8 #LORA MATRIX A and B RANK
LORA_ALPHA = 16 #SCALE FACTOR IN MULTIPLICATION
'''
Alpha is a scaling factor -- it changes how the adaptation layer's weights affect the base model's.
Higher alpha means the LoRA layers act more strongly on the base model.
A lot of the early LoRA examples (e.g. Alpaca-LoRA, etc) tend to use a low rank, like 8, 16, or 32, with roughly double that value for alpha
'''
LORA_DROPOUT= 0.05 #RANDOM WEIGHTS DROPOUT FOR AVOIDING OVERFITTING
LORA_TARGET_MODULES = [
    "q_proj",
    "k_proj",
    "v_proj",
    "o_proj", #MULTI-HEAD ATTENTION WEIGHTS + Output Layer
]

EPOCHS = 15
BATCH_SIZE = 32 #128 Is the prefered value (lower to fit in Colab)
MICRO_BATCH_SIZE = 8 #32 #4
GRADIENT_ACCUMULATION_STEPS = BATCH_SIZE // MICRO_BATCH_SIZE
LEARNING_RATE = 2e-4 #Standard learning rate
WARMUP_RATIO = 0.1

Now we need to load the model and its associated tokenizer. Choose here the number of bits for loading the models. Remember that lower bits mean lower precision, and thus a drop in performance.

In [ ]:
bits = "4" #@param ["4", "8", "full"]

In [ ]:
#-------------------
#   LOAD MODEL
#-------------------

from transformers import AutoModelForCausalLM, BitsAndBytesConfig, AutoTokenizer
import torch
from peft import prepare_model_for_kbit_training, LoraConfig, get_peft_model

tokenizer = AutoTokenizer.from_pretrained("1024m/Llama-3.2-3B-Instruct-Base", use_fast=False)

# base model here, choose between 4, 8 bits or full precision
if bits == "8":
    bnb_config = BitsAndBytesConfig(
        load_in_8bit=True
        # Removed the invalid 8-bit parameters!
    )
    model = AutoModelForCausalLM.from_pretrained(
        BASE_MODEL,
        quantization_config=bnb_config,
        device_map="auto"
    )
    # Prepare only if quantized
    model = prepare_model_for_kbit_training(model)

elif bits == "4":
    bnb_config = BitsAndBytesConfig(
        load_in_4bit=True,
        bnb_4bit_use_double_quant=True,
        bnb_4bit_quant_type="nf4",
        bnb_4bit_compute_dtype=torch.float16
    )
    model = AutoModelForCausalLM.from_pretrained(
        BASE_MODEL,
        quantization_config=bnb_config,
        device_map="auto"
    )
    # Prepare only if quantized
    model = prepare_model_for_kbit_training(model)

else:
    model = AutoModelForCausalLM.from_pretrained(
        BASE_MODEL,
        device_map="auto"
    )

# ADD LORA MODULES
config = LoraConfig(
    r=LORA_R,
    lora_alpha=LORA_ALPHA,
    target_modules=LORA_TARGET_MODULES,
    lora_dropout=LORA_DROPOUT,
    bias="none",
    task_type="CAUSAL_LM",
)

model = get_peft_model(model, config)
model.print_trainable_parameters()

# LLaMA doesn't have a default pad token, so we usually set it to the End-Of-Sequence (EOS) token
tokenizer.pad_token = tokenizer.eos_token

training_arguments = transformers.TrainingArguments(
    per_device_train_batch_size=MICRO_BATCH_SIZE,
    gradient_accumulation_steps=GRADIENT_ACCUMULATION_STEPS,
    warmup_ratio=WARMUP_RATIO,
    num_train_epochs=EPOCHS,
    learning_rate=LEARNING_RATE,
    weight_decay=0.001, # Weight decay to apply to all layers except bias/LayerNorm weights
    lr_scheduler_type = "linear",  # Linear decay of Learning Rate
    fp16=True,
    logging_strategy = "steps",
    logging_steps=1,
    optim="adamw_torch",
    eval_strategy="epoch",
    save_strategy="epoch",
    output_dir=OUTPUT_DIR,
    save_total_limit=1,
    label_names=["labels"]
)

# Initialize the collator
# Swap out DataCollatorForLanguageModeling for Seq2Seq
data_collator = transformers.DataCollatorForSeq2Seq(
    tokenizer=tokenizer,
    model=model, # Passing the model is optional but recommended for padding behavior
    padding=True,
    return_tensors="pt"
)

# istantiate a Trainer object using the hyper-params we defined earlier
trainer = transformers.Trainer(
    model=model,
    train_dataset=train_data,
    eval_dataset=validation_data,
    args=training_arguments,
    data_collator=data_collator
)
model.config.use_cache = False

if torch.cuda.device_count() > 1:
    # keeps Trainer from trying its own DataParallelism when more than 1 gpu is available
    model.is_parallelizable = True
    model.model_parallel = True

Loading weights:   0%|          | 0/254 [00:00<?, ?it/s]

warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

trainable params: 4,587,520 || all params: 3,217,337,344 || trainable%: 0.1426

In [ ]:
#-------------------
#    TRAIN & SAVE
#-------------------
trainer.train()
model.save_pretrained(OUTPUT_DIR)

If you need to clear memory from the gpu, uncomment this code and run it.

**WARNING**: this will delete the `model` variable and delete anything was stored on the GPU!

In [ ]:
import gc
del model
gc.collect()
torch.cuda.empty_cache()

In [ ]:
# Reload model in FP16 and merge it with LoRA adapter weights - SAVE FULL MODEL
from peft import PeftModel
base_model = AutoModelForCausalLM.from_pretrained(
    BASE_MODEL,
    low_cpu_mem_usage=True,
    return_dict=True,
    torch_dtype=torch.float16,
    device_map="auto"
)
model = PeftModel.from_pretrained(base_model, "HCNLP-Llama-3.2-3B-Instruct-LLamini", offload_folder="offload/")
model = model.merge_and_unload()

# Reload tokenizer to save it
tokenizer = AutoTokenizer.from_pretrained("1024m/Llama-3.2-3B-Instruct-Base", use_fast=False)

model.save_pretrained("HCNLP-Llama-3.2-3B-Instruct-LLamini_final")
tokenizer.save_pretrained("HCNLP-Llama-3.2-3B-Instruct-LLamini_final")

`torch_dtype` is deprecated! Use `dtype` instead!

Loading weights:   0%|          | 0/254 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

('HCNLP-Llama-3.2-3B-Instruct-LLamini_final/tokenizer_config.json',
 'HCNLP-Llama-3.2-3B-Instruct-LLamini_final/chat_template.jinja',
 'HCNLP-Llama-3.2-3B-Instruct-LLamini_final/tokenizer.json')

In [ ]:
#!pip install -U huggingface_hub

In [ ]:
# 1. Initialize the API
from huggingface_hub import HfApi
api = HfApi(token="YOUR_HF_WRITE_TOKEN")

# 3. Create the repository on Hugging Face (exist_ok=True means it won't crash if it's already there)
api.create_repo(repo_id="m-polignano/HCNLP-Llama-3.2-3B-Instruct-LLamini", exist_ok=True, repo_type="model")
api.upload_folder(repo_id="m-polignano/HCNLP-Llama-3.2-3B-Instruct-LLamini",folder_path="/content/HCNLP-Llama-3.2-3B-Instruct-LLamini_final",repo_type="model")

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...i_final/model.safetensors:   0%|          | 31.4MB / 6.43GB

  ...mini_final/tokenizer.json: 100%|##########| 17.2MB / 17.2MB

CommitInfo(commit_url='https://huggingface.co/m-polignano/HCNLP-Llama-3.2-3B-Instruct-LLamini/commit/682ada0eaf047a446c4dba7d839c01c866f0aa43', commit_message='Upload folder using huggingface_hub', commit_description='', oid='682ada0eaf047a446c4dba7d839c01c866f0aa43', pr_url=None, repo_url=RepoUrl('https://huggingface.co/m-polignano/HCNLP-Llama-3.2-3B-Instruct-LLamini', endpoint='https://huggingface.co', repo_type='model', repo_id='m-polignano/HCNLP-Llama-3.2-3B-Instruct-LLamini'), pr_revision=None, pr_num=None)

## Upload the model to Huggingface

If you want to share the model with the community (or just to share it between servers), you can push it to the HuggingFace hub by using:

```python
model.push_to_hub("my-awesome-model")
```

Or you can push it directly when saving, at the end of the training procedure:

```python
model.save_pretrained(OUTPUT_DIR, push_to_hub=True, repo_name="my-awesome-model")
```

Of course you first need to [create](https://huggingface.co/docs/hub/security-tokens) an API token from HuggingFace:
- go on your profile
- click on Edit Profile
- on the left you will find "Access Tokens"
- create a new token by pressing on "New Token"
- give it a name and make sure it's set on "write"

After this, just copy it and login using `huggingface-cli`

#Inference: generating answers

In this Notebook we will see how to use the model we trained earlier for generating answers on new data, maybe a test set. Here we will load it from Huggingface (but if you have saved it on your colab it's almost the same), we will se some examples and we will ask the model to answer.

In [ ]:
import torch
from transformers import pipeline

model_id = "1024m/Llama-3.2-3B-Instruct-Base"
pipe = pipeline(
    "text-generation",
    model=model_id,
    torch_dtype=torch.bfloat16,
    device_map="auto",
)
messages = [
    {"role": "system", "content": "You are a very helpful assistant. Answer questions as best you can."},
    {"role": "user", "content": "What is the purpose of the `LLM` class in the Lamini Python package?"},
]
outputs = pipe(
    messages,
    max_new_tokens=256,
)
print(outputs[0]["generated_text"][-1])

`torch_dtype` is deprecated! Use `dtype` instead!

Loading weights:   0%|          | 0/254 [00:00<?, ?it/s]

Passing `generation_config` together with generation-related arguments=({'max_new_tokens'}) is deprecated and will be removed in future versions. Please pass either a `generation_config` object OR all generation parameters explicitly, but not both.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

{'role': 'assistant', 'content': "I'm not familiar with the specific Lamini Python package you're referring to. However, I can tell you about the LLaMA model, which is a popular large language model developed by Meta AI.\n\nLLaMA is not a Python class, but rather a pre-trained language model that can be used in various applications, including text generation, language translation, and more. It's a large transformer-based model that has been trained on a massive dataset of text.\n\nIf you're referring to a different package or implementation of LLaMA in Python, I'd be happy to try and help you further. Can you please provide more context or information about the Lamini Python package and its `LLM` class?"}

In [ ]:
import torch
from transformers import pipeline

model_id = "m-polignano/HCNLP-Llama-3.2-3B-Instruct-LLamini"
pipe = pipeline(
    "text-generation",
    model=model_id,
    torch_dtype=torch.bfloat16,
    device_map="auto",
)
messages = [
    {"role": "system", "content": "You are a very helpful assistant. Answer questions as best you can."},
    {"role": "user", "content": "What is the purpose of the `LLM` class in the Lamini Python package?"},
]
outputs = pipe(
    messages,
    max_new_tokens=256,
)
print(outputs[0]["generated_text"][-1])

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
`torch_dtype` is deprecated! Use `dtype` instead!

model.safetensors:   0%|          | 0.00/6.43G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/254 [00:00<?, ?it/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

generation_config.json:   0%|          | 0.00/183 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/296 [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/17.2M [00:00<?, ?B/s]

Passing `generation_config` together with generation-related arguments=({'max_new_tokens'}) is deprecated and will be removed in future versions. Please pass either a `generation_config` object OR all generation parameters explicitly, but not both.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

{'role': 'assistant', 'content': 'The `LLM` class in the Lamini Python package is used to interface with the Lamini LLM Engine. The LLM Engine is a powerful tool for training and fine-tuning language models, and the `LLM` class provides a simple and easy-to-use interface for working with the engine.'}

In [ ]:
import datasets
from datasets import load_dataset
#FORMAT DATA
instruction_dataset_df = load_dataset("kotzeje/lamini_docs.jsonl", split="train", streaming=True)

prompt_template_LLaMa = '''<|begin_of_text|><|start_header_id|>system<|end_header_id|>

You are a very helpful assistant. Answer questions as best you can.<|eot_id|><|start_header_id|>user<|end_header_id|>

{question}<|eot_id|><|start_header_id|>assistant<|end_header_id|>
'''

text_with_prompt_template=[]
answers = []
questions = []
for row in instruction_dataset_df:
  question = row["question"]
  answer = row["answer"]
  questions.append(question)
  answers.append(answer)

  text_with_prompt_template.append(prompt_template_LLaMa.format(question=question))
print(text_with_prompt_template[0])
#No answers are included into the prompts

<|begin_of_text|><|start_header_id|>system<|end_header_id|>

You are a very helpful assistant. Answer questions as best you can.<|eot_id|><|start_header_id|>user<|end_header_id|>

How can I evaluate the performance and quality of the generated text from Lamini models?<|eot_id|><|start_header_id|>assistant<|end_header_id|>

In [ ]:
# inference
import numpy as np
from transformers import AutoTokenizer
genAnswers = []
z = 400
tokenizer = AutoTokenizer.from_pretrained("m-polignano/HCNLP-Llama-3.2-3B-Instruct-LLamini",fast=False)
with torch.no_grad():
  # LLaMA doesn't have a default pad token, so we usually set it to the End-Of-Sequence (EOS) token

  tokenizer.pad_token = tokenizer.eos_token

  for t in text_with_prompt_template[400:420]:
    tokenized_inputs = tokenizer(t, return_tensors="pt", padding=True, truncation=True).to(pipe.model.device)

    gen_outputs = pipe.model.generate(
      **tokenized_inputs,
      return_dict_in_generate=False,
      output_scores=False,
      max_new_tokens=128,
    )

    # decoding and printing
    for i in range(len(gen_outputs)):
      output = tokenizer.decode(gen_outputs[i], skip_special_tokens=True)
    print("Question:" + questions[z]+"\n")
    print("Real Answer:" + answers[z]+"\n")
    print("Predicted Answer:" + output.split("assistant\n")[-1])
    print("#########################################")
    genAnswers.append(output.split("assistant\n")[-1])
    z = z+1

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Question:Can Lamini have conversations with me, like a friend?

Real Answer:LLM Engine is a language model that can be used to generate responses to conversations. However, it is not designed to be a friend or a substitute for human interaction. Its purpose is to assist with specific tasks and provide helpful responses based on the input it receives.

Predicted Answer:No, Lamini is a language model that can only process text inputs and generate text outputs. It does not have the ability to engage in conversations or have personal interactions.
#########################################

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Question:Can you provide an example use case where Lamini outperforms ChatGPT in handling internal engineering documentation?

Real Answer:An example use case where Lamini outperforms ChatGPT is in handling internal engineering documentation. While ChatGPT with retrieval may lack sufficient context to synthesize information accurately, Lamini's LLM, trained on 100% of the Lamini documentation, possesses specific knowledge, can aggregate information from different sections of documentation, and steer the conversation back to relevant topics.

Predicted Answer:Lamini can be used to generate internal engineering documentation by providing a clear and concise description of the model's architecture and training process. This can help engineers understand the inner workings of the model and make informed decisions about its deployment and maintenance. In contrast, ChatGPT may struggle to provide detailed technical information about the model's architecture, as its primary focus is on generating human-like text for customer-facing applications.
#########################################

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Question:Are Lamini and LangChain both focused on language model development, or do they have distinct purposes?

Real Answer:Both Lamini and LangChain are focused on language model development but with distinct purposes. Lamini aims to democratize language model training, allowing developers to create models specific to their use cases easily. LangChain, on the other hand, focuses on managing sequences of calls and integrating various tools, providing a framework for building complex language-based workflows.

Predicted Answer:Lamini is a library for building language models, while LangChain is a framework for building conversational interfaces. They have different focuses and purposes.
#########################################

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Question:Where can I get my Lamini API key?

Real Answer:To obtain your Lamini API key, simply navigate to the Lamini website at https://lamini.ai and log in to your account. Once you've securely logged in, you'll be directed to your account page, where you can access and manage your API key. This unique API key serves as your authentication token, granting you access to Lamini's powerful language models and API services. By following this straightforward process, you can swiftly retrieve your API key and seamlessly integrate it into your applications, unlocking the full potential of Lamini's advanced natural language processing capabilities. Whether you're developing chatbots, language translation systems, or any other AI-powered applications, your Lamini API key is the gateway to harnessing the power of state-of-the-art language models.

Predicted Answer:You can get your Lamini API key by signing up for a free account on the Lamini website. Once you have created an account, you will be able to access your API key through the dashboard.
#########################################

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Question:Hi hi hib hi hi

Real Answer:Hi, I am a Lamini Bot, I am here to help you with questions related to Lamini

Predicted Answer:Lamini is a python library that makes it easy to work with text data. It provides a simple and efficient way to train models and generate text. Lamini is a very powerful tool that can be used for a variety of tasks, from simple text classification to complex language translation.
#########################################

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Question:How does Lamini compare to other libraries or frameworks for training language models?

Real Answer:Lamini is a state-of-the-art library for training and customizing language models, with a focus on ease of use, flexibility, and performance. Compared to other libraries or frameworks, Lamini offers several unique features, such as support for multi-modal learning, privacy-preserving techniques, and natural language explanations for model predictions. Additionally, Lamini provides pre-built models and templates for various tasks, as well as tools for interpretability and explainability of customized models. Overall, Lamini is a powerful and versatile tool for language modeling, with many advantages over other libraries or frameworks.

Predicted Answer:Lamini is a unique library that focuses on generating human-like text through language models. While other libraries may offer similar functionality, Lamini's emphasis on generating coherent and contextually relevant text sets it apart. Additionally, Lamini's ease of use and flexibility make it an attractive option for developers looking to integrate language models into their applications.
#########################################

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Question:How does Lamini AI handle requests for generating text that requires domain-specific technical knowledge, such as medical or legal terminology?

Real Answer:Lamini AI offers features for generating text with domain-specific technical knowledge, such as medical or legal terminology. It can use existing datasets to generate text that is accurate and up-to-date with the latest industry standards. Additionally, Lamini AI can be trained to recognize and use domain-specific terminology in generated text.

Predicted Answer:Lamini AI can handle requests for generating text that requires domain-specific technical knowledge by incorporating relevant terminology and jargon from the specific domain into the generated text. This can be achieved through the use of specialized training data and fine-tuning of the language model to recognize and incorporate domain-specific terms and phrases. Additionally, Lamini AI can also provide tools and features to help users incorporate domain-specific knowledge into their generated text, such as the ability to specify specific keywords or phrases to include in the generated text.
#########################################

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Question:What are the supported Python versions for Lamini Python package?

Real Answer:Lamini supports Python 3.6 and above.

Predicted Answer:The Lamini Python package supports Python 3.7 and 3.8.
#########################################

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Question:Does Lamini have the capability to generate text that incorporates suspense or cliffhangers in storytelling?

Real Answer:Yes, Lamini has the ability to generate text that incorporates suspense or cliffhangers in storytelling. With its advanced language generation capabilities, Lamini can create engaging and thrilling narratives that keep readers on the edge of their seats. Whether it's a mystery, thriller, or any other genre, Lamini can craft a story that leaves readers wanting more.

Predicted Answer:Lamini has the capability to generate text that incorporates suspense or cliffhangers in storytelling. This can be achieved by using techniques such as leaving certain details or plot points unresolved, or by creating a sense of tension or uncertainty in the narrative. By using these techniques, Lamini can help to keep readers engaged and invested in the story, and create a sense of anticipation for what is to come.
#########################################

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Question:How does Lamini AI optimize training speed and reduce the number of training iterations?

Real Answer:Lamini AI reduces the number of training iterations by providing a hosted data generator for training LLMs, weights and all, without spinning up any GPUs, in just a few lines of code from the Lamini library. This allows developers to quickly and easily customize models and fine-tune them on modest datasets. Lamini AI also provides enterprise features like virtual private cloud (VPC) deployments to further optimize training speed.

Predicted Answer:Lamini AI uses techniques such as parallel processing and caching to optimize training speed. Additionally, it reduces the number of training iterations by using early stopping and checkpointing to save the model at intermediate checkpoints.
#########################################

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Question:Can Lamini be used for tasks like generating text or answering questions without any technical knowledge?

Real Answer:Yes, Lamini can be used for tasks like generating text or answering questions without any technical knowledge. It is designed to be user-friendly and accessible to anyone, regardless of their technical background.

Predicted Answer:Yes, Lamini can be used for tasks like generating text or answering questions without any technical knowledge. It provides a user-friendly interface and natural language processing capabilities, making it accessible to users without requiring extensive technical expertise.
#########################################

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Question:Does Lamini offer tools or features to monitor and track the performance and usage of LLMs in production environments?

Real Answer:Yes, Lamini offers tools and features to monitor and track the performance and usage of LLMs in production environments. These include metrics such as accuracy, loss, and perplexity, as well as visualization tools to analyze model behavior and identify areas for improvement. Additionally, Lamini provides logging and alerting capabilities to notify developers of any issues or anomalies in the model's performance.

Predicted Answer:Yes, Lamini offers tools and features to monitor and track the performance and usage of LLMs in production environments. These include metrics such as latency, throughput, and accuracy, as well as features such as logging and monitoring for debugging and troubleshooting.
#########################################

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Question:How can I control the level of specificity or randomness in Lamini's responses?

Real Answer:Lamini’s default temperature is 0 and in order to increase the randomness, set `random=True` when calling the model using LLM Engine.__call__

Predicted Answer:Lamini allows for control over the level of specificity and randomness in responses through the use of specific language and keywords in the input prompt. By incorporating more specific language, the model is able to provide more detailed and accurate responses. On the other hand, adding randomness or ambiguity to the input prompt can result in more creative and open-ended responses. Additionally, Lamini's language generation capabilities can be fine-tuned and customized to suit specific use cases and requirements.
#########################################

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Question:Why do we blush when we're embarrassed?

Real Answer:Let’s keep the discussion relevant to Lamini.

Predicted Answer:Blushing is a natural response to feelings of embarrassment or self-consciousness. It is a physiological response that involves the dilation of blood vessels near the surface of the skin, causing the skin to flush with blood. This can make the face appear red or pink. The exact mechanism of blushing is not fully understood, but it is thought to be related to the release of neurotransmitters such as dopamine and serotonin, which can stimulate blood vessel dilation. Blushing can also be a social signal that conveys embarrassment or shyness, which can help to diffuse tension and promote social interaction.
#########################################

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Question:Are there any performance considerations when using Lamini in production systems with high request volumes?

Real Answer:There may be performance considerations when using Lamini in production systems with high request volumes. It is recommended to test Lamini's performance under expected load and consider implementing caching or load balancing strategies to optimize performance.

Predicted Answer:Yes, there are performance considerations when using Lamini in production systems with high request volumes. Lamini is designed to handle high concurrency and throughput, but it can still be affected by the underlying infrastructure and the complexity of the input data. To optimize performance, it's recommended to use a distributed architecture, caching, and efficient data storage. Additionally, monitoring and logging can help identify bottlenecks and optimize the system for better performance.
#########################################

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Question:Do Lamini and LangChain offer similar capabilities when it comes to prompt management and optimization?

Real Answer:Both Lamini and LangChain offer capabilities related to prompt management and optimization. They provide tools and utilities to manage prompts effectively and optimize model performance based on specific prompts or use cases. However, the implementation and specific features may differ between the two platforms.

Predicted Answer:Yes, Lamini and LangChain offer similar capabilities when it comes to prompt management and optimization. Both platforms provide tools and techniques for refining and fine-tuning prompts to achieve desired outcomes, as well as strategies for managing and optimizing prompt performance.
#########################################

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Question:Does the documentation provide information on performance optimization or best practices for using the code?

Real Answer:Yes, the documentation has information on running a model using a batch interface as well as using a real-time interface. Besides that, the LLM Engine will optimize performance automatically.

Predicted Answer:No, the documentation does not provide information on performance optimization or best practices for using the code.
#########################################

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Question:Are there any mechanisms in Lamini to mitigate bias or fairness issues in LLM training?

Real Answer:Yes, Lamini provides mechanisms to mitigate bias and fairness issues in LLM training. One approach is to use techniques such as adversarial training or data augmentation to increase the diversity of the training data and reduce bias. Additionally, Lamini allows for fine-tuning of pre-trained models on specific domains or use cases, which can help to reduce bias and improve fairness. Finally, Lamini provides tools for analyzing and interpreting the behavior of LLMs, which can help to identify and address any bias or fairness issues that may arise during training.

Predicted Answer:Yes, Lamini provides mechanisms to mitigate bias and fairness issues in LLM training. These mechanisms include data preprocessing techniques, such as removing sensitive information and handling missing values, as well as algorithms that promote fairness and reduce bias, such as fairness-aware optimization methods and debiasing techniques. Additionally, Lamini provides tools for data visualization and analysis, allowing users to identify and address potential bias in their data.
#########################################

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Question:Can you explain the process of adding data using the `add_data()` function? What formats are supported for training data?

Real Answer:The `add_data()` function in the `Program` class allows you to add training data to your program. It supports both singleton and list formats for the examples parameter. If the examples parameter is a list, related information can be grouped together. The function `value_to_dict()` is used to convert the examples to a dictionary format.

Predicted Answer:Adding data to a model using the `add_data()` function involves providing the training data in a specific format. The supported formats for training data include CSV and JSON. The data should be in a pandas DataFrame or a list of lists, where each inner list represents a row of data. The columns in the data should match the column names specified in the `add_data()` function. The data should also be properly formatted, with each row being a dictionary where the keys are the column names and the values are the corresponding data points.
#########################################
Question:do you offer a rest API?

Real Answer:Yes, we do offer rest API endpoint for model inference, you can find details here: https://lamini-ai.github.io/API/completions/. Currently access to model fine-tuning API endpoint is only available to our early customers. To join the early access waitlist, contact us at https://www.lamini.ai/contact

Predicted Answer:Yes, Lamini offers a REST API for interacting with the model.
#########################################

In [ ]:
from nltk.translate.bleu_score import sentence_bleu
scores = []
for i in range(len(genAnswers)):
  reference = [answers[i]]
  test = genAnswers[i]
  score = sentence_bleu(reference, test)
  scores.append(score)

print("Mean BLEU Score: "+str(sum(scores) / len(scores)))

Mean BLEU Score: 0.15953361320575232

In [ ]:
import locale
locale.getpreferredencoding = lambda: "UTF-8"
!pip install rouge-score

from rouge_score import rouge_scorer

scorer = rouge_scorer.RougeScorer(['rougeL'], use_stemmer=False)

scores = []
for i in range(len(genAnswers)):
  reference = answers[i]
  test = genAnswers[i]
  score = scorer.score(reference, test)['rougeL'][2] #f1measure
  scores.append(score)
mean = sum(scores) / len(scores)
print("Mean ROUGE-L Score: "+ str(mean))

Requirement already satisfied: rouge-score in /usr/local/lib/python3.12/dist-packages (0.1.2)
Requirement already satisfied: absl-py in /usr/local/lib/python3.12/dist-packages (from rouge-score) (1.4.0)
Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (from rouge-score) (3.9.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from rouge-score) (2.0.2)
Requirement already satisfied: six>=1.14.0 in /usr/local/lib/python3.12/dist-packages (from rouge-score) (1.17.0)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk->rouge-score) (8.3.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk->rouge-score) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk->rouge-score) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk->rouge-score) (4.67.3)
Mean ROUGE-L Score: 0.0887621553965324

In [ ]:
import gc
del pipe
del tokenizer
gc.collect()
torch.cuda.empty_cache()

# Unsloth
## Installation

To run this, press "*Runtime*" and press "*Run all*" on a **free** Tesla T4 Google Colab instance!
<div class="align-center">
<a href="https://unsloth.ai/"><img src="https://github.com/unslothai/unsloth/raw/main/images/unsloth%20new%20logo.png" width="115"></a>
<a href="https://discord.gg/unsloth"><img src="https://github.com/unslothai/unsloth/raw/main/images/Discord button.png" width="145"></a>
<a href="https://unsloth.ai/docs/"><img src="https://github.com/unslothai/unsloth/blob/main/images/documentation%20green%20button.png?raw=true" width="125"></a> Join Discord if you need help + ⭐ <i>Star us on <a href="https://github.com/unslothai/unsloth">Github</a> </i> ⭐
</div>

To install Unsloth on your local device, follow [our guide](https://unsloth.ai/docs/get-started/install). This notebook is licensed [LGPL-3.0](https://github.com/unslothai/notebooks?tab=LGPL-3.0-1-ov-file#readme).

You will learn how to do [data prep](#Data), how to [train](#Train), how to [run the model](#Inference), & how to save it

In [ ]:
%%capture
import os, re
if "COLAB_" not in "".join(os.environ.keys()):
    !pip install unsloth  # Do this in local & cloud setups
else:
    import torch; v = re.match(r'[\d]{1,}\.[\d]{1,}', str(torch.__version__)).group(0)
    xformers = 'xformers==' + {'2.10':'0.0.34','2.9':'0.0.33.post1','2.8':'0.0.32.post2'}.get(v, "0.0.34")
    !pip install sentencepiece protobuf "datasets==4.3.0" "huggingface_hub>=0.34.0" hf_transfer
    !pip install --no-deps unsloth_zoo bitsandbytes accelerate {xformers} peft trl triton unsloth
!pip install transformers==4.56.2
!pip install --no-deps trl==0.22.2

In [ ]:
from unsloth import FastLanguageModel
import torch
max_seq_length = 1024 # Choose any! We auto support RoPE Scaling internally!
dtype = None # None for auto detection. Float16 for Tesla T4, V100, Bfloat16 for Ampere+
load_in_4bit = True # Use 4bit quantization to reduce memory usage. Can be False.

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = "unsloth/Llama-3.2-3B-Instruct", # or choose "unsloth/Llama-3.2-1B-Instruct"
    max_seq_length = max_seq_length,
    dtype = dtype,
    load_in_4bit = load_in_4bit,
    # token = "YOUR_HF_TOKEN", # HF Token for gated models
)

🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.
🦥 Unsloth Zoo will now patch everything to make training faster!
==((====))==  Unsloth 2026.2.1: Fast Llama patching. Transformers: 4.56.2.
   \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.563 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.10.0+cu128. CUDA: 7.5. CUDA Toolkit: 12.8. Triton: 3.6.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.34. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

model.safetensors:   0%|          | 0.00/2.35G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/234 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/454 [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/17.2M [00:00<?, ?B/s]

chat_template.jinja: 0.00B [00:00, ?B/s]

We now add LoRA adapters so we only need to update 1 to 10% of all parameters!

In [ ]:
model = FastLanguageModel.get_peft_model(
    model,
    r = 16, # Choose any number > 0 ! Suggested 8, 16, 32, 64, 128
    target_modules = ["q_proj", "k_proj", "v_proj", "o_proj",
                      "gate_proj", "up_proj", "down_proj",],
    lora_alpha = 16,
    lora_dropout = 0, # Supports any, but = 0 is optimized
    bias = "none",    # Supports any, but = "none" is optimized
    # [NEW] "unsloth" uses 30% less VRAM, fits 2x larger batch sizes!
    use_gradient_checkpointing = "unsloth", # True or "unsloth" for very long context
    random_state = 3407,
    use_rslora = False,  # We support rank stabilized LoRA
    loftq_config = None, # And LoftQ
)

Unsloth 2026.2.1 patched 28 layers with 28 QKV layers, 28 O layers and 28 MLP layers.

<a name="Data"></a>
### Data Prep
We now use the `Llama-3.2` format for conversation style finetunes. We use [Maxime Labonne's FineTome-100k](https://huggingface.co/datasets/mlabonne/FineTome-100k) dataset in ShareGPT style. But we convert it to HuggingFace's normal multiturn format `("role", "content")` instead of `("from", "value")`/ Llama-3 renders multi turn conversations like below:

```
<|begin_of_text|><|start_header_id|>user<|end_header_id|>

Hello!<|eot_id|><|start_header_id|>assistant<|end_header_id|>

Hey there! How are you?<|eot_id|><|start_header_id|>user<|end_header_id|>

I'm great thanks!<|eot_id|>
```

We use our `get_chat_template` function to get the correct chat template. We support `zephyr, chatml, mistral, llama, alpaca, vicuna, vicuna_old, phi3, llama3` and more.

In [ ]:
from unsloth.chat_templates import get_chat_template

tokenizer = get_chat_template(
    tokenizer,
    chat_template = "llama-3.2",
)

def formatting_prompts_func(examples):
    convos = examples["conversations"]
    texts = [tokenizer.apply_chat_template(convo, tokenize = False, add_generation_prompt = False) for convo in convos]
    return { "text" : texts, }

from datasets import load_dataset
dataset = load_dataset("mlabonne/FineTome-100k", split = "train")

We now use `standardize_sharegpt` to convert ShareGPT style datasets into HuggingFace's generic format. This changes the dataset from looking like:
```
{"from": "system", "value": "You are an assistant"}
{"from": "human", "value": "What is 2+2?"}
{"from": "gpt", "value": "It's 4."}
```
to
```
{"role": "system", "content": "You are an assistant"}
{"role": "user", "content": "What is 2+2?"}
{"role": "assistant", "content": "It's 4."}
```

In [ ]:
from unsloth.chat_templates import standardize_sharegpt
dataset = standardize_sharegpt(dataset)
dataset = dataset.map(formatting_prompts_func, batched = True,)

Unsloth: Standardizing formats (num_proc=6):   0%|          | 0/100000 [00:00<?, ? examples/s]

Map:   0%|          | 0/100000 [00:00<?, ? examples/s]

We look at how the conversations are structured for item 5:

In [ ]:
dataset[5]["conversations"]

[{'content': 'How do astronomers determine the original wavelength of light emitted by a celestial body at rest, which is necessary for measuring its speed using the Doppler effect?',
  'role': 'user'},
 {'content': 'Astronomers make use of the unique spectral fingerprints of elements found in stars. These elements emit and absorb light at specific, known wavelengths, forming an absorption spectrum. By analyzing the light received from distant stars and comparing it to the laboratory-measured spectra of these elements, astronomers can identify the shifts in these wavelengths due to the Doppler effect. The observed shift tells them the extent to which the light has been redshifted or blueshifted, thereby allowing them to calculate the speed of the star along the line of sight relative to Earth.',
  'role': 'assistant'}]

In [ ]:
print(dataset[5]["text"])

'<|begin_of_text|><|start_header_id|>system<|end_header_id|>\n\nCutting Knowledge Date: December 2023\nToday Date: 26 July 2024\n\n<|eot_id|><|start_header_id|>user<|end_header_id|>\n\nHow do astronomers determine the original wavelength of light emitted by a celestial body at rest, which is necessary for measuring its speed using the Doppler effect?<|eot_id|><|start_header_id|>assistant<|end_header_id|>\n\nAstronomers make use of the unique spectral fingerprints of elements found in stars. These elements emit and absorb light at specific, known wavelengths, forming an absorption spectrum. By analyzing the light received from distant stars and comparing it to the laboratory-measured spectra of these elements, astronomers can identify the shifts in these wavelengths due to the Doppler effect. The observed shift tells them the extent to which the light has been redshifted or blueshifted, thereby allowing them to calculate the speed of the star along the line of sight relative to Earth.<|eot_id|>'

<a name="Train"></a>
### Train the model
Now let's train our model. We do 60 steps to speed things up, but you can set `num_train_epochs=1` for a full run, and turn off `max_steps=None`. We also support `DPOTrainer` and `GRPOTrainer` for reinforcement learning!!

In [ ]:
from trl import SFTConfig, SFTTrainer
from transformers import DataCollatorForSeq2Seq
trainer = SFTTrainer(
    model = model,
    tokenizer = tokenizer,
    train_dataset = dataset,
    dataset_text_field = "text",
    max_seq_length = max_seq_length,
    data_collator = DataCollatorForSeq2Seq(tokenizer = tokenizer),
    packing = False, # Can make training 5x faster for short sequences.
    args = SFTConfig(
        per_device_train_batch_size = 2,
        gradient_accumulation_steps = 4,
        warmup_steps = 5,
        # num_train_epochs = 1, # Set this for 1 full training run.
        max_steps = 60,
        learning_rate = 2e-4,
        logging_steps = 1,
        optim = "adamw_8bit",
        weight_decay = 0.001,
        lr_scheduler_type = "linear",
        seed = 3407,
        output_dir = "outputs",
        report_to = "none", # Use TrackIO/WandB etc
    ),
)

Unsloth: Tokenizing ["text"] (num_proc=6):   0%|          | 0/100000 [00:00<?, ? examples/s]

We also use Unsloth's `train_on_completions` method to only train on the assistant outputs and ignore the loss on the user's inputs.

In [ ]:
from unsloth.chat_templates import train_on_responses_only
trainer = train_on_responses_only(
    trainer,
    instruction_part = "<|start_header_id|>user<|end_header_id|>\n\n",
    response_part = "<|start_header_id|>assistant<|end_header_id|>\n\n",
)

Map (num_proc=6):   0%|          | 0/100000 [00:00<?, ? examples/s]

Filter (num_proc=6):   0%|          | 0/100000 [00:00<?, ? examples/s]

Unsloth: Removed 693 out of 100000 samples from train_dataset where all labels were -100 (no response found after truncation). This prevents NaN loss during training.

We verify masking is actually done:

In [ ]:
tokenizer.decode(trainer.train_dataset[5]["input_ids"])

'<|begin_of_text|><|begin_of_text|><|start_header_id|>system<|end_header_id|>\n\nCutting Knowledge Date: December 2023\nToday Date: 26 July 2024\n\n<|eot_id|><|start_header_id|>user<|end_header_id|>\n\nHow do astronomers determine the original wavelength of light emitted by a celestial body at rest, which is necessary for measuring its speed using the Doppler effect?<|eot_id|><|start_header_id|>assistant<|end_header_id|>\n\nAstronomers make use of the unique spectral fingerprints of elements found in stars. These elements emit and absorb light at specific, known wavelengths, forming an absorption spectrum. By analyzing the light received from distant stars and comparing it to the laboratory-measured spectra of these elements, astronomers can identify the shifts in these wavelengths due to the Doppler effect. The observed shift tells them the extent to which the light has been redshifted or blueshifted, thereby allowing them to calculate the speed of the star along the line of sight relative to Earth.<|eot_id|>'

In [ ]:
space = tokenizer(" ", add_special_tokens = False).input_ids[0]
tokenizer.decode([space if x == -100 else x for x in trainer.train_dataset[5]["labels"]])

'                                                                  Astronomers make use of the unique spectral fingerprints of elements found in stars. These elements emit and absorb light at specific, known wavelengths, forming an absorption spectrum. By analyzing the light received from distant stars and comparing it to the laboratory-measured spectra of these elements, astronomers can identify the shifts in these wavelengths due to the Doppler effect. The observed shift tells them the extent to which the light has been redshifted or blueshifted, thereby allowing them to calculate the speed of the star along the line of sight relative to Earth.<|eot_id|>'

We can see the System and Instruction prompts are successfully masked!

In [ ]:
# @title Show current memory stats
gpu_stats = torch.cuda.get_device_properties(0)
start_gpu_memory = round(torch.cuda.max_memory_reserved() / 1024 / 1024 / 1024, 3)
max_memory = round(gpu_stats.total_memory / 1024 / 1024 / 1024, 3)
print(f"GPU = {gpu_stats.name}. Max memory = {max_memory} GB.")
print(f"{start_gpu_memory} GB of memory reserved.")

GPU = Tesla T4. Max memory = 14.563 GB.
3.07 GB of memory reserved.

In [ ]:
trainer_stats = trainer.train()

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 99,307 | Num Epochs = 1 | Total steps = 60
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 4
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 4 x 1) = 8
 "-____-"     Trainable parameters = 24,313,856 of 3,237,063,680 (0.75% trained)

Unsloth: Will smartly offload gradients to save VRAM!

In [ ]:
# @title Show final memory and time stats
used_memory = round(torch.cuda.max_memory_reserved() / 1024 / 1024 / 1024, 3)
used_memory_for_lora = round(used_memory - start_gpu_memory, 3)
used_percentage = round(used_memory / max_memory * 100, 3)
lora_percentage = round(used_memory_for_lora / max_memory * 100, 3)
print(f"{trainer_stats.metrics['train_runtime']} seconds used for training.")
print(
    f"{round(trainer_stats.metrics['train_runtime']/60, 2)} minutes used for training."
)
print(f"Peak reserved memory = {used_memory} GB.")
print(f"Peak reserved memory for training = {used_memory_for_lora} GB.")
print(f"Peak reserved memory % of max memory = {used_percentage} %.")
print(f"Peak reserved memory for training % of max memory = {lora_percentage} %.")

459.4731 seconds used for training.
7.66 minutes used for training.
Peak reserved memory = 4.342 GB.
Peak reserved memory for training = 1.272 GB.
Peak reserved memory % of max memory = 29.815 %.
Peak reserved memory for training % of max memory = 8.734 %.

<a name="Inference"></a>
### Inference
Let's run the model! You can change the instruction and input - leave the output blank!



We use `min_p = 0.1` and `temperature = 1.5`. Read this [Tweet](https://x.com/menhguin/status/1826132708508213629) for more information on why.

In [ ]:
from unsloth.chat_templates import get_chat_template

tokenizer = get_chat_template(
    tokenizer,
    chat_template = "llama-3.2",
)
FastLanguageModel.for_inference(model) # Enable native 2x faster inference

messages = [
    {"role": "user", "content": "Continue the fibonacci sequence: 1, 1, 2, 3, 5, 8,"},
]
inputs = tokenizer.apply_chat_template(
    messages,
    tokenize = True,
    add_generation_prompt = True, # Must add for generation
    return_tensors = "pt",
).to("cuda")

outputs = model.generate(input_ids = inputs, max_new_tokens = 64, use_cache = True,
                         temperature = 1.5, min_p = 0.1)
tokenizer.batch_decode(outputs)

The attention mask is not set and cannot be inferred from input because pad token is same as eos token. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.

['<|begin_of_text|><|start_header_id|>system<|end_header_id|>\n\nCutting Knowledge Date: December 2023\nToday Date: 26 July 2024\n\n<|eot_id|><|start_header_id|>user<|end_header_id|>\n\nContinue the fibonacci sequence: 1, 1, 2, 3, 5, 8,<|eot_id|><|start_header_id|>assistant<|end_header_id|>\n\nThe Fibonacci sequence is a series of numbers in which each number is the sum of the two preceding numbers. The sequence is: 0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144,']

 You can also use a `TextStreamer` for continuous inference - so you can see the generation token by token, instead of waiting the whole time!

In [ ]:
FastLanguageModel.for_inference(model) # Enable native 2x faster inference

messages = [
    {"role": "user", "content": "Continue the fibonacci sequence: 1, 1, 2, 3, 5, 8,"},
]
inputs = tokenizer.apply_chat_template(
    messages,
    tokenize = True,
    add_generation_prompt = True, # Must add for generation
    return_tensors = "pt",
).to("cuda")

from transformers import TextStreamer
text_streamer = TextStreamer(tokenizer, skip_prompt = True)
_ = model.generate(input_ids = inputs, streamer = text_streamer, max_new_tokens = 128,
                   use_cache = True, temperature = 1.5, min_p = 0.1)

1, 13, 21, 34, 55, 89.<|eot_id|>

<a name="Save"></a>
### Saving, loading finetuned models
To save the final model as LoRA adapters, either use Hugging Face's `push_to_hub` for an online save or `save_pretrained` for a local save.

**[NOTE]** This ONLY saves the LoRA adapters, and not the full model. To save to 16bit or GGUF, scroll down!

In [ ]:
model.save_pretrained("llama_lora")  # Local saving
tokenizer.save_pretrained("llama_lora")
# model.push_to_hub("your_name/llama_lora", token = "YOUR_HF_TOKEN") # Online saving
# tokenizer.push_to_hub("your_name/llama_lora", token = "YOUR_HF_TOKEN") # Online saving

('llama_lora/tokenizer_config.json',
 'llama_lora/special_tokens_map.json',
 'llama_lora/chat_template.jinja',
 'llama_lora/tokenizer.json')

Now if you want to load the LoRA adapters we just saved for inference, set `False` to `True`:

In [ ]:
if True:
    from unsloth import FastLanguageModel
    model, tokenizer = FastLanguageModel.from_pretrained(
        model_name = "llama_lora", # YOUR MODEL YOU USED FOR TRAINING
        max_seq_length = max_seq_length,
        dtype = dtype,
        load_in_4bit = load_in_4bit,
    )
    FastLanguageModel.for_inference(model) # Enable native 2x faster inference

messages = [
    {"role": "user", "content": "Describe a tall tower in the capital of France."},
]
inputs = tokenizer.apply_chat_template(
    messages,
    tokenize = True,
    add_generation_prompt = True, # Must add for generation
    return_tensors = "pt",
).to("cuda")

from transformers import TextStreamer
text_streamer = TextStreamer(tokenizer, skip_prompt = True)
_ = model.generate(input_ids = inputs, streamer = text_streamer, max_new_tokens = 128,
                   use_cache = True, temperature = 1.5, min_p = 0.1)

==((====))==  Unsloth 2026.2.1: Fast Llama patching. Transformers: 4.56.2.
   \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.563 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.10.0+cu128. CUDA: 7.5. CUDA Toolkit: 12.8. Triton: 3.6.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.34. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!
The Eiffel Tower, located in Paris, the capital of France, is a towering iron lattice structure that stands 324 meters (1,063 feet) tall. It is an iconic symbol of the city and a major tourist attraction. The Eiffel Tower was built for the 1889 World's Fair, held in Paris, and its construction required the development of advanced engineering techniques to support its height. It was intended to be a temporary structure, but it has become a permanent part of the Parisian skyline and a cultural landmark around the world.<|eot_id|>

You can also use Hugging Face's `AutoPeftModelForCausalLM`. Only use this if you do not have `unsloth` installed. It can be hopelessly slow, since `4bit` model downloading is not supported, and Unsloth's **inference is 2x faster**.

In [ ]:
if False:
    # I highly do NOT suggest - use Unsloth if possible
    from peft import AutoPeftModelForCausalLM
    from transformers import AutoTokenizer
    model = AutoPeftModelForCausalLM.from_pretrained(
        "llama_lora", # YOUR MODEL YOU USED FOR TRAINING
        load_in_4bit = load_in_4bit,
    )
    tokenizer = AutoTokenizer.from_pretrained("llama_lora")

### Saving to float16 for VLLM

We also support saving to `float16` directly. Select `merged_16bit` for float16 or `merged_4bit` for int4. We also allow `lora` adapters as a fallback. Use `push_to_hub_merged` to upload to your Hugging Face account! You can go to https://huggingface.co/settings/tokens for your personal tokens. See [our docs](https://unsloth.ai/docs/basics/inference-and-deployment) for more deployment options.

In [ ]:
# Merge to 16bit
if False: model.save_pretrained_merged("llama_finetune_16bit", tokenizer, save_method = "merged_16bit",)
if False: model.push_to_hub_merged("HF_USERNAME/llama_finetune_16bit", tokenizer, save_method = "merged_16bit", token = "YOUR_HF_TOKEN")

# Merge to 4bit
if False: model.save_pretrained_merged("llama_finetune_4bit", tokenizer, save_method = "merged_4bit",)
if False: model.push_to_hub_merged("HF_USERNAME/llama_finetune_4bit", tokenizer, save_method = "merged_4bit", token = "YOUR_HF_TOKEN")

# Just LoRA adapters
if False:
    model.save_pretrained("llama_lora")
    tokenizer.save_pretrained("llama_lora")
if False:
    model.push_to_hub("HF_USERNAME/llama_lora", token = "YOUR_HF_TOKEN")
    tokenizer.push_to_hub("HF_USERNAME/llama_lora", token = "YOUR_HF_TOKEN")

### GGUF / llama.cpp Conversion
To save to `GGUF` / `llama.cpp`, we support it natively now! We clone `llama.cpp` and we default save it to `q8_0`. We allow all methods like `q4_k_m`. Use `save_pretrained_gguf` for local saving and `push_to_hub_gguf` for uploading to HF.

Some supported quant methods (full list on our [docs page](https://unsloth.ai/docs/basics/inference-and-deployment/saving-to-gguf)):
* `q8_0` - Fast conversion. High resource use, but generally acceptable.
* `q4_k_m` - Recommended. Uses Q6_K for half of the attention.wv and feed_forward.w2 tensors, else Q4_K.
* `q5_k_m` - Recommended. Uses Q6_K for half of the attention.wv and feed_forward.w2 tensors, else Q5_K.

[**NEW**] To finetune and auto export to Ollama, try our [Ollama notebook](https://colab.research.google.com/github/unslothai/notebooks/blob/main/nb/Llama3_(8B)-Ollama.ipynb)

In [ ]:
# Save to 8bit Q8_0
if False: model.save_pretrained_gguf("llama_finetune", tokenizer,)
# Remember to go to https://huggingface.co/settings/tokens for a token!
# And change hf to your username!
if False: model.push_to_hub_gguf("HF_USERNAME/llama_finetune", tokenizer, token = "YOUR_HF_TOKEN")

# Save to 16bit GGUF
if False: model.save_pretrained_gguf("llama_finetune", tokenizer, quantization_method = "f16")
if False: model.push_to_hub_gguf("HF_USERNAME/llama_finetune", tokenizer, quantization_method = "f16", token = "YOUR_HF_TOKEN")

# Save to q4_k_m GGUF
if False: model.save_pretrained_gguf("llama_finetune", tokenizer, quantization_method = "q4_k_m")
if False: model.push_to_hub_gguf("HF_USERNAME/llama_finetune", tokenizer, quantization_method = "q4_k_m", token = "YOUR_HF_TOKEN")

# Save to multiple GGUF options - much faster if you want multiple!
if False:
    model.push_to_hub_gguf(
        "HF_USERNAME/llama_finetune", # Change hf to your username!
        tokenizer,
        quantization_method = ["q4_k_m", "q8_0", "q5_k_m",],
        token = "YOUR_HF_TOKEN", # Get a token at https://huggingface.co/settings/tokens
    )

And we're done! If you have any questions on Unsloth, we have a [Discord](https://discord.gg/unsloth) channel! If you find any bugs or want to keep updated with the latest LLM stuff, or need help, join projects etc, feel free to join our Discord!

Some other resources:
1. Looking to use Unsloth locally? Read our [Installation Guide](https://unsloth.ai/docs/get-started/install) for details on installing Unsloth on Windows, Docker, AMD, Intel GPUs.
2. Learn how to do Reinforcement Learning with our [RL Guide and notebooks](https://unsloth.ai/docs/get-started/reinforcement-learning-rl-guide).
3. Read our guides and notebooks for [Text-to-speech (TTS)](https://unsloth.ai/docs/basics/text-to-speech-tts-fine-tuning) and [vision](https://unsloth.ai/docs/basics/vision-fine-tuning) model support.
4. Explore our [LLM Tutorials Directory](https://unsloth.ai/docs/models/tutorials-how-to-fine-tune-and-run-llms) to find dedicated guides for each model.
5. Need help with Inference? Read our [Inference & Deployment page](https://unsloth.ai/docs/basics/inference-and-deployment) for details on using vLLM, llama.cpp, Ollama etc.

<div class="align-center">
  <a href="https://unsloth.ai"><img src="https://github.com/unslothai/unsloth/raw/main/images/unsloth%20new%20logo.png" width="115"></a>
  <a href="https://discord.gg/unsloth"><img src="https://github.com/unslothai/unsloth/raw/main/images/Discord.png" width="145"></a>
  <a href="https://unsloth.ai/docs/"><img src="https://github.com/unslothai/unsloth/blob/main/images/documentation%20green%20button.png?raw=true" width="125"></a>

  Join Discord if you need help + ⭐️ <i>Star us on <a href="https://github.com/unslothai/unsloth">Github</a> </i> ⭐️

  <b>This notebook and all Unsloth notebooks are licensed [LGPL-3.0](https://github.com/unslothai/notebooks?tab=LGPL-3.0-1-ov-file#readme)</b>
</div>

# Unsloth GRPO

In [ ]:
%%capture
import os
os.environ["UNSLOTH_VLLM_STANDBY"] = "1" # [NEW] Extra 30% context lengths!
if "COLAB_" not in "".join(os.environ.keys()):
    # If you're not in Colab, just use pip install or uv pip install
    !pip install unsloth vllm
else:
    pass # For Colab / Kaggle, we need extra instructions hidden below \/

In [ ]:
#@title Colab Extra Install { display-mode: "form" }
%%capture
import os
!pip install --upgrade -qqq uv
if "COLAB_" not in "".join(os.environ.keys()):
    # If you're not in Colab, just use pip install!
    !pip install unsloth vllm
else:
    try: import numpy, PIL; _numpy = f'numpy=={numpy.__version__}'; _pil = f'pillow=={PIL.__version__}'
    except: _numpy = "numpy"; _pil = "pillow"
    try: import subprocess; is_t4 = "Tesla T4" in str(subprocess.check_output(["nvidia-smi"]))
    except: is_t4 = False
    _vllm, _triton = ('vllm==0.9.2', 'triton==3.2.0') if is_t4 else ('vllm==0.15.1', 'triton')
    !uv pip install -qqq --upgrade {_vllm} {_numpy} {_pil} torchvision bitsandbytes xformers unsloth
    !uv pip install -qqq {_triton}
!uv pip install transformers==4.56.2
!uv pip install --no-deps trl==0.22.2

Goal: To convert `Llama-3.2-1B-Instruct` into a reasoning model via GRPO by using OpenR1's Math dataset.

We first pre fine-tune the model to make GRPO skip trying to match formatting - this speeds GRPO up.

In [ ]:
from unsloth import FastLanguageModel
import torch
max_seq_length = 1024 # Can increase for longer reasoning traces
lora_rank = 32 # Larger rank = smarter, but slower

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = "meta-llama/Llama-3.2-1B-Instruct",
    max_seq_length = max_seq_length,
    load_in_4bit = False, # False for LoRA 16bit
    fast_inference = True, # Enable vllm fast inference
    max_lora_rank = lora_rank,
    gpu_memory_utilization = 0.9, # Reduce if out of memory
)

model = FastLanguageModel.get_peft_model(
    model,
    r = lora_rank, # Choose any number > 0 ! Suggested 8, 16, 32, 64, 128
    target_modules = [
        "q_proj", "k_proj", "v_proj", "o_proj",
        "gate_proj", "up_proj", "down_proj",
    ], # Remove QKVO if out of memory
    lora_alpha = lora_rank,
    use_gradient_checkpointing = "unsloth", # Enable long context finetuning
    random_state = 3407,
)

🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.
INFO 02-20 17:55:37 [__init__.py:244] Automatically detected platform cuda.
ERROR 02-20 17:55:41 [fa_utils.py:57] Cannot use FA version 2 is not supported due to FA2 is only supported on devices with compute capability >= 8
🦥 Unsloth Zoo will now patch everything to make training faster!
INFO 02-20 17:55:56 [vllm_utils.py:723] Unsloth: Patching vLLM v1 graph capture
INFO 02-20 17:55:56 [vllm_utils.py:752] Unsloth: Patching vLLM v0 graph capture
==((====))==  Unsloth 2026.2.1: Fast Llama patching. Transformers: 4.56.2. vLLM: 0.9.2.
   \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.563 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.7.0+cu126. CUDA: 7.5. CUDA Toolkit: 12.6. Triton: 3.2.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.30. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!
Unsloth: vLLM loading unsloth/Llama-3.2-1B-Instruct with actual GPU utilization = 89.13%
Unsloth: Your GPU has CUDA compute capability 7.5 with VRAM = 14.56 GB.
Unsloth: Using conservativeness = 1.0. Chunked prefill tokens = 1024. Num Sequences = 48.
Unsloth: vLLM's KV Cache can use up to 10.49 GB. Also swap space = 0 GB.
Unsloth: `cudagraph_mode` is not in `from vllm.config import CompilationConfig`
Unsloth: Disabling `disable_cascade_attn` in vLLM to allow for better on policy RL!
INFO 02-20 17:56:39 [config.py:841] This model supports multiple tasks: {'reward', 'embed', 'generate', 'classify'}. Defaulting to 'generate'.

`torch_dtype` is deprecated! Use `dtype` instead!

WARNING 02-20 17:56:39 [config.py:3371] Casting torch.bfloat16 to torch.float16.
INFO 02-20 17:56:39 [config.py:1472] Using max model len 1024
WARNING 02-20 17:56:39 [arg_utils.py:1735] Compute Capability < 8.0 is not supported by the V1 Engine. Falling back to V0.
INFO 02-20 17:56:45 [config.py:2285] Chunked prefill is enabled with max_num_batched_tokens=4096.
INFO 02-20 17:56:45 [llm_engine.py:230] Initializing a V0 LLM engine (v0.9.2) with config: model='unsloth/Llama-3.2-1B-Instruct', speculative_config=None, tokenizer='unsloth/Llama-3.2-1B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config={}, tokenizer_revision=None, trust_remote_code=False, dtype=torch.float16, max_seq_len=1024, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto,  device_config=cuda, decoding_config=DecodingConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_backend=''), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None), seed=0, served_model_name=unsloth/Llama-3.2-1B-Instruct, num_scheduler_steps=1, multi_step_stream_outputs=True, enable_prefix_caching=True, chunked_prefill_enabled=True, use_async_output_proc=True, pooler_config=None, compilation_config={"level":0,"debug_dump_path":"","cache_dir":"","backend":"inductor","custom_ops":[],"splitting_ops":[],"use_inductor":true,"compile_sizes":[],"inductor_compile_config":{"epilogue_fusion":true,"max_autotune":false,"shape_padding":true,"trace.enabled":false,"triton.cudagraphs":true,"debug":false,"dce":true,"memory_planning":true,"coordinate_descent_tuning":false,"trace.graph_diagram":false,"compile_threads":4,"group_fusion":true,"disable_progress":false,"verbose_progress":true,"triton.multi_kernel":0,"triton.use_block_ptr":true,"triton.enable_persistent_tma_matmul":true,"triton.autotune_at_compile_time":false,"triton.cooperative_reductions":false,"cuda.compile_opt_level":"-O2","cuda.enable_cuda_lto":true,"combo_kernels":false,"benchmark_combo_kernel":true,"combo_kernel_foreach_dynamic_shapes":true,"enable_auto_functionalized_v2":false},"inductor_passes":{},"use_cudagraph":true,"cudagraph_num_of_warmups":1,"cudagraph_capture_sizes":[48,40,32,24,16,8,4,2,1],"cudagraph_copy_inputs":false,"full_cuda_graph":true,"max_capture_size":48,"local_cache_dir":null}, use_cached_outputs=False,

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.json:   0%|          | 0.00/17.2M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/454 [00:00<?, ?B/s]

chat_template.jinja: 0.00B [00:00, ?B/s]

generation_config.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

INFO 02-20 17:56:48 [cuda.py:311] Cannot use FlashAttention-2 backend for Volta and Turing GPUs.
INFO 02-20 17:56:48 [cuda.py:360] Using XFormers backend.
INFO 02-20 17:56:49 [parallel_state.py:1076] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, TP rank 0, EP rank 0
INFO 02-20 17:56:49 [model_runner.py:1171] Starting to load model unsloth/Llama-3.2-1B-Instruct...
INFO 02-20 17:56:52 [weight_utils.py:292] Using model weights format ['*.safetensors']

model.safetensors:   0%|          | 0.00/2.47G [00:00<?, ?B/s]

INFO 02-20 17:57:24 [weight_utils.py:308] Time spent downloading weights for unsloth/Llama-3.2-1B-Instruct: 32.697833 seconds
INFO 02-20 17:57:24 [weight_utils.py:345] No model.safetensors.index.json found in remote.

Loading safetensors checkpoint shards:   0% Completed | 0/1 [00:00<?, ?it/s]

INFO 02-20 17:57:31 [default_loader.py:272] Loading weights took 6.71 seconds
INFO 02-20 17:57:31 [punica_selector.py:19] Using PunicaWrapperGPU.
INFO 02-20 17:57:34 [model_runner.py:1203] Model loading took 2.3802 GiB and 40.527155 seconds
INFO 02-20 17:57:41 [worker.py:294] Memory profiling takes 6.45 seconds
INFO 02-20 17:57:41 [worker.py:294] the current vLLM instance can use total_gpu_memory (14.56GiB) x gpu_memory_utilization (0.89) = 12.98GiB
INFO 02-20 17:57:41 [worker.py:294] model weights take 2.38GiB; non_torch_memory takes 0.03GiB; PyTorch activation peak memory takes 0.31GiB; the rest of the memory reserved for KV Cache is 10.26GiB.
INFO 02-20 17:57:42 [executor_base.py:113] # cuda blocks: 21005, # CPU blocks: 0
INFO 02-20 17:57:42 [executor_base.py:118] Maximum concurrency for 1024 tokens per request: 328.20x
INFO 02-20 17:57:42 [vllm_utils.py:757] Unsloth: Running patched vLLM v0 `capture_model`.
INFO 02-20 17:57:42 [model_runner.py:1513] Capturing cudagraphs for decoding. This may lead to unexpected consequences if the model is not static. To run the model in eager mode, set 'enforce_eager=True' or use '--enforce-eager' in the CLI. If out-of-memory error occurs during cudagraph capture, consider decreasing `gpu_memory_utilization` or switching to eager mode. You can also reduce the `max_num_seqs` as needed to decrease memory usage.

Capturing CUDA graph shapes:   0%|          | 0/9 [00:00<?, ?it/s]

INFO 02-20 17:57:44 [model_runner.py:1671] Graph capturing finished in 2 secs, took 0.08 GiB
INFO 02-20 17:57:44 [vllm_utils.py:764] Unsloth: Patched vLLM v0 graph capture finished in 2 secs.
INFO 02-20 17:57:45 [llm_engine.py:428] init engine (profile, create kv cache, warmup model) took 11.62 seconds
Unsloth: Just some info: will skip parsing ['attention_norm', 'norm', 'post_feedforward_layernorm', 'q_norm', 'layer_norm2', 'ffn_norm', 'k_norm', 'norm1', 'post_attention_layernorm', 'input_layernorm', 'pre_feedforward_layernorm', 'post_layernorm', 'layer_norm1', 'norm2']

Some weights of LlamaForCausalLM were not initialized from the model checkpoint at unsloth/Llama-3.2-1B-Instruct and are newly initialized: ['lm_head.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Performing substitution for additional_keys=set()
Unsloth: Just some info: will skip parsing ['attention_norm', 'cross_attn_input_layernorm', 'norm', 'post_feedforward_layernorm', 'q_norm', 'layer_norm2', 'ffn_norm', 'k_norm', 'norm1', 'cross_attn_post_attention_layernorm', 'post_attention_layernorm', 'input_layernorm', 'pre_feedforward_layernorm', 'post_layernorm', 'layer_norm1', 'norm2']

tokenizer_config.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/454 [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/17.2M [00:00<?, ?B/s]

chat_template.jinja: 0.00B [00:00, ?B/s]

Unsloth 2026.2.1 patched 16 layers with 16 QKV layers, 16 O layers and 16 MLP layers.

In [ ]:
messages = [
    {"role": "user", "content": "Solve x^5 + 3x^4 - 10 = 3."},
]
inputs = tokenizer.apply_chat_template(
    messages,
    add_generation_prompt = True,
    return_tensors = "pt",
    return_dict = True,
    reasoning_effort = "low",
).to(model.device)
from transformers import TextStreamer
_ = model.generate(**inputs, max_new_tokens = 512, use_cache = True, streamer = TextStreamer(tokenizer))

<|begin_of_text|><|start_header_id|>system<|end_header_id|>

Cutting Knowledge Date: December 2023
Today Date: 20 Feb 2026

<|eot_id|><|start_header_id|>user<|end_header_id|>

Solve x^5 + 3x^4 - 10 = 3.<|eot_id|><|start_header_id|>assistant<|end_header_id|>

To solve the equation x^5 + 3x^4 - 10 = 3, we need to isolate the variable x.

First, let's add 10 to both sides of the equation:

x^5 + 3x^4 = 3 + 10
x^5 + 3x^4 = 13

Next, let's subtract 13 from both sides of the equation:

x^5 + 3x^4 - 13 = 0

Now, we have a polynomial equation of degree 5. Unfortunately, this equation does not have a simple closed-form solution. However, we can try to find the roots using numerical methods or graphing.

Using numerical methods, we can find that one of the roots of the equation is approximately x = 1.324.

To find the other roots, we can use numerical methods such as the Newton-Raphson method or graphing. However, these methods are not provided here as they are complex and require a significant amount of computational power.

Therefore, the solution to the equation x^5 + 3x^4 - 10 = 3 is x ≈ 1.324.<|eot_id|>

Let's call the model as is:

In [ ]:
text = "What is the sqrt of 101?"

from vllm import SamplingParams
sampling_params = SamplingParams(
    temperature = 1.0,
    top_k = 50,
    max_tokens = 512,
)
output = model.fast_generate(
    [text],
    sampling_params = sampling_params,
    lora_request = None,
)[0].outputs[0].text

output

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

'?\nA) 10\nB) 11\nC) 16\nD) 15.61\nThe best answer is D.'

### GRPO chat template
Since we're using a base model, we should set a chat template. You can make your own chat template as well!
1. DeepSeek uses `<think>` and `</think>`, but this is **not** necessary - you can customize it however you like!
2. A `system_prompt` is recommended to at least guide the model's responses.

In [ ]:
reasoning_start = "<start_working_out>" # Acts as <think>
reasoning_end   = "<end_working_out>"   # Acts as </think>
solution_start  = "<SOLUTION>"
solution_end    = "</SOLUTION>"

system_prompt = \
f"""You are given a problem.
Think about the problem and provide your working out.
Place it between {reasoning_start} and {reasoning_end}.
Then, provide your solution between {solution_start}{solution_end}"""
system_prompt

'You are given a problem.\nThink about the problem and provide your working out.\nPlace it between <start_working_out> and <end_working_out>.\nThen, provide your solution between <SOLUTION></SOLUTION>'

We create a simple chat template below. Notice `add_generation_prompt` includes prepending `<start_working_out>` to guide the model to start its reasoning process.

In [ ]:
chat_template = \
    "{% if messages[0]['role'] == 'system' %}"\
        "{{ messages[0]['content'] + eos_token }}"\
        "{% set loop_messages = messages[1:] %}"\
    "{% else %}"\
        "{{ '{system_prompt}' + eos_token }}"\
        "{% set loop_messages = messages %}"\
    "{% endif %}"\
    "{% for message in loop_messages %}"\
        "{% if message['role'] == 'user' %}"\
            "{{ message['content'] }}"\
        "{% elif message['role'] == 'assistant' %}"\
            "{{ message['content'] + eos_token }}"\
        "{% endif %}"\
    "{% endfor %}"\
    "{% if add_generation_prompt %}{{ '{reasoning_start}' }}"\
    "{% endif %}"

# Replace with our specific template:
chat_template = chat_template\
    .replace("'{system_prompt}'",   f"'{system_prompt}'")\
    .replace("'{reasoning_start}'", f"'{reasoning_start}'")
tokenizer.chat_template = chat_template

Let's see how our chat template behaves on an example:

In [ ]:
tokenizer.apply_chat_template([
    {"role" : "user", "content" : "What is 1+1?"},
    {"role" : "assistant", "content" : f"{reasoning_start}I think it's 2.{reasoning_end}{solution_start}2{solution_end}"},
    {"role" : "user", "content" : "What is 2+2?"},
], tokenize = False, add_generation_prompt = True)

"You are given a problem.\nThink about the problem and provide your working out.\nPlace it between <start_working_out> and <end_working_out>.\nThen, provide your solution between <SOLUTION></SOLUTION><|eot_id|>What is 1+1?<start_working_out>I think it's 2.<end_working_out><SOLUTION>2</SOLUTION><|eot_id|>What is 2+2?<start_working_out>"

### Pre fine-tuning for formatting
We now use a subset of NVIDIA's [Open Math Reasoning dataset](https://huggingface.co/datasets/nvidia/OpenMathReasoning) which was filtered to only include high quality DeepSeek R1 traces.

We'll only filter ~59 or so examples to first "prime" / pre fine-tune the model to understand our custom GRPO formatting.

In [ ]:
from datasets import load_dataset
import pandas as pd
import numpy as np

dataset = load_dataset("unsloth/OpenMathReasoning-mini", split = "cot")
dataset = dataset.to_pandas()[
    ["expected_answer", "problem", "generated_solution"]
]

# Try converting to number - if not, replace with NaN
is_number = pd.to_numeric(pd.Series(dataset["expected_answer"]), errors = "coerce").notnull()
# Select only numbers
dataset = dataset.iloc[np.where(is_number)[0]]

dataset

,expected_answer,problem,generated_solution
0,14,Given $\sqrt{x^2+165}-\sqrt{x^2-52}=7$ and $x$...,"<think>\nOkay, let's see. I need to solve the ..."
6,-2,Find the value of the parameter $a$ for which ...,"<think>\nOkay, so I need to find the value of ..."
9,18,What is the sum of all real numbers $x$ for wh...,"<think>\nOkay, so I need to solve the equation..."
13,2,Evaluate the sum \(\sum_{n=1}^\infty \frac{\ph...,"<think>\nOkay, so I need to evaluate the infin..."
17,30,What is the largest positive integer that divi...,"<think>\nAlright, so I need to find the larges..."
...,...,...,...
19243,244,"Let \( p \), \( q \), and \( r \) be the disti...","<think>\nOkay, so I need to find the value of ..."
19245,1,A bug is on the $0$ of a number line. At any p...,"<think>\nOkay, so I have this problem where a ..."
19247,4,A bus left point X for point Y. Two hours late...,"<think>\nOkay, let's tackle this problem step ..."
19248,18,Each interior angle of a regular n-gon measure...,"<think>\nOkay, let's see. I need to find the n..."
19250,0.8960,Find the probability that the second blue resu...,"<think>\nOkay, so I need to find the probabili..."

We have to format the dataset to follow our GRPO style formatting:

In [ ]:
def format_dataset(x):
    expected_answer = x["expected_answer"]
    problem = x["problem"]

    # Remove generated <think> and </think>
    thoughts = x["generated_solution"]
    thoughts = thoughts.replace("<think>", "").replace("</think>", "")

    # Strip newlines on left and right
    thoughts = thoughts.strip()
    # Add our custom formatting
    final_prompt = \
        reasoning_start + thoughts + reasoning_end + \
        solution_start + expected_answer + solution_end
    return [
        {"role" : "system",    "content" : system_prompt},
        {"role" : "user",      "content" : problem},
        {"role" : "assistant", "content" : final_prompt},
    ]

dataset["Messages"] = dataset.apply(format_dataset, axis = 1)

Check to see if it worked:

In [ ]:
tokenizer.apply_chat_template(dataset["Messages"][0], tokenize = False)

"You are given a problem.\nThink about the problem and provide your working out.\nPlace it between <start_working_out> and <end_working_out>.\nThen, provide your solution between <SOLUTION></SOLUTION><|eot_id|>Given $\\sqrt{x^2+165}-\\sqrt{x^2-52}=7$ and $x$ is positive, find all possible values of $x$.<start_working_out>Okay, let's see. I need to solve the equation √(x² + 165) - √(x² - 52) = 7, and find all positive values of x. Hmm, radicals can be tricky, but maybe if I can eliminate the square roots by squaring both sides. Let me try that.\n\nFirst, let me write down the equation again to make sure I have it right:\n\n√(x² + 165) - √(x² - 52) = 7.\n\nOkay, so the idea is to isolate one of the radicals and then square both sides. Let me try moving the second radical to the other side:\n\n√(x² + 165) = 7 + √(x² - 52).\n\nNow, if I square both sides, maybe I can get rid of the square roots. Let's do that:\n\n(√(x² + 165))² = (7 + √(x² - 52))².\n\nSimplifying the left side:\n\nx² + 165 = 49 + 14√(x² - 52) + (√(x² - 52))².\n\nThe right side is expanded using the formula (a + b)² = a² + 2ab + b². So the right side becomes 7² + 2*7*√(x² - 52) + (√(x² - 52))², which is 49 + 14√(x² - 52) + (x² - 52).\n\nSo putting it all together:\n\nx² + 165 = 49 + 14√(x² - 52) + x² - 52.\n\nHmm, let's simplify the right side. The x² terms will cancel out, right? Let's subtract x² from both sides:\n\n165 = 49 + 14√(x² - 52) - 52.\n\nSimplify the constants on the right:\n\n49 - 52 is -3, so:\n\n165 = -3 + 14√(x² - 52).\n\nNow, add 3 to both sides to isolate the radical term:\n\n165 + 3 = 14√(x² - 52).\n\nSo 168 = 14√(x² - 52).\n\nDivide both sides by 14:\n\n168 / 14 = √(x² - 52).\n\n12 = √(x² - 52).\n\nNow, square both sides again to eliminate the square root:\n\n12² = x² - 52.\n\n144 = x² - 52.\n\nAdd 52 to both sides:\n\n144 + 52 = x².\n\n196 = x².\n\nSo x = √196 = 14.\n\nBut wait, since the problem states that x is positive, we only take the positive root. So x = 14.\n\nBut hold on, when dealing with squaring equations, sometimes extraneous solutions can come up. I should check if this solution actually satisfies the original equation.\n\nLet's plug x = 14 back into the original equation:\n\n√(14² + 165) - √(14² - 52) = ?\n\nCalculate each term:\n\n14² is 196.\n\nSo first radical: √(196 + 165) = √361 = 19.\n\nSecond radical: √(196 - 52) = √144 = 12.\n\nSo 19 - 12 = 7, which is exactly the right-hand side. So yes, it checks out.\n\nTherefore, the only solution is x = 14. Since the problem says x is positive, we don't have to consider negative roots. So I think that's the answer.\nTo solve the equation \\(\\sqrt{x^2 + 165} - \\sqrt{x^2 - 52} = 7\\) for positive \\(x\\), we proceed as follows:\n\n1. Start with the given equation:\n   \\[\n   \\sqrt{x^2 + 165} - \\sqrt{x^2 - 52} = 7\n   \\]\n\n2. Isolate one of the square roots by moving \\(\\sqrt{x^2 - 52}\\) to the right side:\n   \\[\n   \\sqrt{x^2 + 165} = 7 + \\sqrt{x^2 - 52}\n   \\]\n\n3. Square both sides to eliminate the square root on the left:\n   \\[\n   (\\sqrt{x^2 + 165})^2 = (7 + \\sqrt{x^2 - 52})^2\n   \\]\n   Simplifying both sides, we get:\n   \\[\n   x^2 + 165 = 49 + 14\\sqrt{x^2 - 52} + (x^2 - 52)\n   \\]\n\n4. Combine like terms on the right side:\n   \\[\n   x^2 + 165 = x^2 - 52 + 49 + 14\\sqrt{x^2 - 52}\n   \\]\n   Simplifying further:\n   \\[\n   x^2 + 165 = x^2 - 3 + 14\\sqrt{x^2 - 52}\n   \\]\n\n5. Subtract \\(x^2\\) from both sides:\n   \\[\n   165 = -3 + 14\\sqrt{x^2 - 52}\n   \\]\n\n6. Add 3 to both sides to isolate the term with the square root:\n   \\[\n   168 = 14\\sqrt{x^2 - 52}\n   \\]\n\n7. Divide both sides by 14:\n   \\[\n   12 = \\sqrt{x^2 - 52}\n   \\]\n\n8. Square both sides again to eliminate the square root:\n   \\[\n   12^2 = x^2 - 52\n   \\]\n   Simplifying:\n   \\[\n   144 = x^2 - 52\n   \\]\n\n9. Add 52 to both sides to solve for \\(x^2\\):\n   \\[\n   196 = x^2\n   \\]\n\n10. Take the positive square root (since \\(x\\) is positive):\n    \\[\n    x = \\sqrt{196} = 14\n    \\]\n\n11. Verify the solution by substituting \\(x = 14\\) back into the original equation:\n    \\[\n    \\sqrt{14^2 + 165} - \\sqrt{14^2 - 52} = \\sqrt{196 + 165} - \\sqrt{196 - 52} = \\sqrt{361} - \\sqrt{144} = 19 - 12 = 7\n    \\]\n    The solution checks out.\n\nThus, the only positive solution is:\n\\[\n\\boxed{14}\n\\]<end_working_out><SOLUTION>14</SOLUTION><|eot_id|>"

Let's truncate the pre fine-tuning dataset to `max_seq_length/2` since we don't want too long reasoning traces.

Note this might take 2 minutes!

In [ ]:
dataset["N"] = dataset["Messages"].apply(lambda x: len(tokenizer.apply_chat_template(x)))

We then tokenize the messages and convert it to a Hugging Face compatible dataset format:

In [ ]:
from datasets import Dataset

dataset["text"] = tokenizer.apply_chat_template(dataset["Messages"].values.tolist(), tokenize = False)
dataset = Dataset.from_pandas(dataset)
dataset

Dataset({
    features: ['expected_answer', 'problem', 'generated_solution', 'Messages', 'N', 'text', '__index_level_0__'],
    num_rows: 7507
})

In [ ]:
dataset["text"][0]

"You are given a problem.\nThink about the problem and provide your working out.\nPlace it between <start_working_out> and <end_working_out>.\nThen, provide your solution between <SOLUTION></SOLUTION><|eot_id|>Given $\\sqrt{x^2+165}-\\sqrt{x^2-52}=7$ and $x$ is positive, find all possible values of $x$.<start_working_out>Okay, let's see. I need to solve the equation √(x² + 165) - √(x² - 52) = 7, and find all positive values of x. Hmm, radicals can be tricky, but maybe if I can eliminate the square roots by squaring both sides. Let me try that.\n\nFirst, let me write down the equation again to make sure I have it right:\n\n√(x² + 165) - √(x² - 52) = 7.\n\nOkay, so the idea is to isolate one of the radicals and then square both sides. Let me try moving the second radical to the other side:\n\n√(x² + 165) = 7 + √(x² - 52).\n\nNow, if I square both sides, maybe I can get rid of the square roots. Let's do that:\n\n(√(x² + 165))² = (7 + √(x² - 52))².\n\nSimplifying the left side:\n\nx² + 165 = 49 + 14√(x² - 52) + (√(x² - 52))².\n\nThe right side is expanded using the formula (a + b)² = a² + 2ab + b². So the right side becomes 7² + 2*7*√(x² - 52) + (√(x² - 52))², which is 49 + 14√(x² - 52) + (x² - 52).\n\nSo putting it all together:\n\nx² + 165 = 49 + 14√(x² - 52) + x² - 52.\n\nHmm, let's simplify the right side. The x² terms will cancel out, right? Let's subtract x² from both sides:\n\n165 = 49 + 14√(x² - 52) - 52.\n\nSimplify the constants on the right:\n\n49 - 52 is -3, so:\n\n165 = -3 + 14√(x² - 52).\n\nNow, add 3 to both sides to isolate the radical term:\n\n165 + 3 = 14√(x² - 52).\n\nSo 168 = 14√(x² - 52).\n\nDivide both sides by 14:\n\n168 / 14 = √(x² - 52).\n\n12 = √(x² - 52).\n\nNow, square both sides again to eliminate the square root:\n\n12² = x² - 52.\n\n144 = x² - 52.\n\nAdd 52 to both sides:\n\n144 + 52 = x².\n\n196 = x².\n\nSo x = √196 = 14.\n\nBut wait, since the problem states that x is positive, we only take the positive root. So x = 14.\n\nBut hold on, when dealing with squaring equations, sometimes extraneous solutions can come up. I should check if this solution actually satisfies the original equation.\n\nLet's plug x = 14 back into the original equation:\n\n√(14² + 165) - √(14² - 52) = ?\n\nCalculate each term:\n\n14² is 196.\n\nSo first radical: √(196 + 165) = √361 = 19.\n\nSecond radical: √(196 - 52) = √144 = 12.\n\nSo 19 - 12 = 7, which is exactly the right-hand side. So yes, it checks out.\n\nTherefore, the only solution is x = 14. Since the problem says x is positive, we don't have to consider negative roots. So I think that's the answer.\nTo solve the equation \\(\\sqrt{x^2 + 165} - \\sqrt{x^2 - 52} = 7\\) for positive \\(x\\), we proceed as follows:\n\n1. Start with the given equation:\n   \\[\n   \\sqrt{x^2 + 165} - \\sqrt{x^2 - 52} = 7\n   \\]\n\n2. Isolate one of the square roots by moving \\(\\sqrt{x^2 - 52}\\) to the right side:\n   \\[\n   \\sqrt{x^2 + 165} = 7 + \\sqrt{x^2 - 52}\n   \\]\n\n3. Square both sides to eliminate the square root on the left:\n   \\[\n   (\\sqrt{x^2 + 165})^2 = (7 + \\sqrt{x^2 - 52})^2\n   \\]\n   Simplifying both sides, we get:\n   \\[\n   x^2 + 165 = 49 + 14\\sqrt{x^2 - 52} + (x^2 - 52)\n   \\]\n\n4. Combine like terms on the right side:\n   \\[\n   x^2 + 165 = x^2 - 52 + 49 + 14\\sqrt{x^2 - 52}\n   \\]\n   Simplifying further:\n   \\[\n   x^2 + 165 = x^2 - 3 + 14\\sqrt{x^2 - 52}\n   \\]\n\n5. Subtract \\(x^2\\) from both sides:\n   \\[\n   165 = -3 + 14\\sqrt{x^2 - 52}\n   \\]\n\n6. Add 3 to both sides to isolate the term with the square root:\n   \\[\n   168 = 14\\sqrt{x^2 - 52}\n   \\]\n\n7. Divide both sides by 14:\n   \\[\n   12 = \\sqrt{x^2 - 52}\n   \\]\n\n8. Square both sides again to eliminate the square root:\n   \\[\n   12^2 = x^2 - 52\n   \\]\n   Simplifying:\n   \\[\n   144 = x^2 - 52\n   \\]\n\n9. Add 52 to both sides to solve for \\(x^2\\):\n   \\[\n   196 = x^2\n   \\]\n\n10. Take the positive square root (since \\(x\\) is positive):\n    \\[\n    x = \\sqrt{196} = 14\n    \\]\n\n11. Verify the solution by substituting \\(x = 14\\) back into the original equation:\n    \\[\n    \\sqrt{14^2 + 165} - \\sqrt{14^2 - 52} = \\sqrt{196 + 165} - \\sqrt{196 - 52} = \\sqrt{361} - \\sqrt{144} = 19 - 12 = 7\n    \\]\n    The solution checks out.\n\nThus, the only positive solution is:\n\\[\n\\boxed{14}\n\\]<end_working_out><SOLUTION>14</SOLUTION><|eot_id|>"

Let's now pre fine-tune the model so it follows our custom GRPO formatting!

In [ ]:
from trl import SFTTrainer, SFTConfig
trainer = SFTTrainer(
    model = model,
    tokenizer = tokenizer,
    train_dataset = dataset,
    args = SFTConfig(
        dataset_text_field = "text",
        per_device_train_batch_size = 2,
        gradient_accumulation_steps = 2, # Use GA to mimic batch size!
        warmup_steps = 10,
        # num_train_epochs = 1, # Set this for 1 full training run.
        max_steps = 100,
        learning_rate = 2e-4, # Reduce to 2e-5 for long training runs
        logging_steps = 5,
        optim = "adamw_8bit",
        weight_decay = 0.01,
        lr_scheduler_type = "linear",
        seed = 3407,
        report_to = "none", # Use this for WandB etc
    ),
)

Unsloth: Tokenizing ["text"] (num_proc=5):   0%|          | 0/7507 [00:00<?, ? examples/s]

🦥 Unsloth: Padding-free auto-enabled, enabling faster training.

In [ ]:
trainer.train()

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 7,507 | Num Epochs = 1 | Total steps = 100
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 2
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 2 x 1) = 4
 "-____-"     Trainable parameters = 22,544,384 of 1,258,358,784 (1.79% trained)

Unsloth: Will smartly offload gradients to save VRAM!

TrainOutput(global_step=100, training_loss=0.9305826616287232, metrics={'train_runtime': 187.2159, 'train_samples_per_second': 2.137, 'train_steps_per_second': 0.534, 'total_flos': 2446363755528192.0, 'train_loss': 0.9305826616287232, 'epoch': 0.05327650506126798})

Let's check if the model has learnt to follow the custom format:

In [ ]:
import gc
for _ in range(5):
    torch.cuda.empty_cache()
    gc.collect()

Yes it did follow the formatting! Great! Let's remove some items before the GRPO step

In [ ]:
del dataset
torch.cuda.empty_cache()
import gc
gc.collect()

0

### Data Prep
<a name="Data"></a>

We're using Hugging Face's [Open R1 Math dataset](https://huggingface.co/datasets/open-r1/DAPO-Math-17k-Processed). You can also utilize OpenAI's famous [GSM8K dataset](https://huggingface.co/datasets/openai/gsm8k)

In [ ]:
from datasets import load_dataset
dataset = load_dataset("open-r1/DAPO-Math-17k-Processed", "en", split = "train")
dataset

README.md: 0.00B [00:00, ?B/s]

en/train-00000-of-00001.parquet:   0%|          | 0.00/5.23M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/14116 [00:00<?, ? examples/s]

Dataset({
    features: ['prompt', 'solution', 'data_source', 'source_prompt', 'ability', 'reward_model', 'extra_info'],
    num_rows: 14116
})

Let's look at the first row:

In [ ]:
dataset[0]["prompt"]

'In triangle $ABC$, $\\sin \\angle A = \\frac{4}{5}$ and $\\angle A < 90^\\circ$. Let $D$ be a point outside triangle $ABC$ such that $\\angle BAD = \\angle DAC$ and $\\angle BDC = 90^\\circ$. Suppose that $AD = 1$ and that $\\frac{BD}{CD} = \\frac{3}{2}$. If $AB + AC$ can be expressed in the form $\\frac{a\\sqrt{b}}{c}$ where $a, b, c$ are pairwise relatively prime integers, find $a + b + c$.'

In [ ]:
dataset[0]["solution"]

'34'

In GSM8K, we notice all answers like about have a ####, so we extract it. But for the Open R1 dataset, we can skip the below.

In [ ]:
def extract_hash_answer(text):
    # if "####" not in text: return None
    # return text.split("####")[1].strip()
    return text
extract_hash_answer(dataset[0]["solution"])

'34'

Let's map the dataset! and see the first row:

In [ ]:
dataset = dataset.map(lambda x: {
    "prompt" : [
        {"role": "system", "content": system_prompt},
        {"role": "user",   "content": x["prompt"]},
    ],
    "answer": extract_hash_answer(x["solution"]),
})
dataset[0]

Map:   0%|          | 0/14116 [00:00<?, ? examples/s]

{'prompt': [{'content': 'You are given a problem.\nThink about the problem and provide your working out.\nPlace it between <start_working_out> and <end_working_out>.\nThen, provide your solution between <SOLUTION></SOLUTION>',
   'role': 'system'},
  {'content': 'In triangle $ABC$, $\\sin \\angle A = \\frac{4}{5}$ and $\\angle A < 90^\\circ$. Let $D$ be a point outside triangle $ABC$ such that $\\angle BAD = \\angle DAC$ and $\\angle BDC = 90^\\circ$. Suppose that $AD = 1$ and that $\\frac{BD}{CD} = \\frac{3}{2}$. If $AB + AC$ can be expressed in the form $\\frac{a\\sqrt{b}}{c}$ where $a, b, c$ are pairwise relatively prime integers, find $a + b + c$.',
   'role': 'user'}],
 'solution': '34',
 'data_source': 'math_dapo',
 'source_prompt': [{'content': 'Solve the following math problem step by step. The last line of your response should be of the form Answer: $Answer (without quotes) where $Answer is the answer to the problem.\n\nIn triangle $ABC$, $\\sin \\angle A = \\frac{4}{5}$ and $\\angle A < 90^\\circ$. Let $D$ be a point outside triangle $ABC$ such that $\\angle BAD = \\angle DAC$ and $\\angle BDC = 90^\\circ$. Suppose that $AD = 1$ and that $\\frac{BD}{CD} = \\frac{3}{2}$. If $AB + AC$ can be expressed in the form $\\frac{a\\sqrt{b}}{c}$ where $a, b, c$ are pairwise relatively prime integers, find $a + b + c$.\n\nRemember to put your answer on its own line after "Answer:".',
   'role': 'user'}],
 'ability': 'MATH',
 'reward_model': {'ground_truth': '34', 'style': 'rule-lighteval/MATH_v2'},
 'extra_info': {'index': '9a9b6eb4-a1cb-49d1-8c1e-62eaf2f74079'},
 'answer': '34'}

We create a regex format to match the reasoning sections and answers:

In [ ]:
import re

# Add optional EOS token matching
solution_end_regex = r"</SOLUTION>[\s]{0,}" + \
    "(?:" + re.escape(tokenizer.eos_token) + ")?"

match_format = re.compile(
    rf"{reasoning_end}.*?"\
    rf"{solution_start}(.+?){solution_end_regex}"\
    rf"[\s]{{0,}}$",
    flags = re.MULTILINE | re.DOTALL
)
match_format

re.compile(r'<end_working_out>.*?<SOLUTION>(.+?)</SOLUTION>[\s]{0,}(?:<\|eot_id\|>)?[\s]{0,}$',
re.MULTILINE|re.DOTALL|re.UNICODE)

We verify it works:

In [ ]:
match_format.findall(
    "Let me think!<end_working_out>"\
    f"<SOLUTION>\n2\n</SOLUTION>",
)

['\n2\n']

In [ ]:
match_format.findall(
    "<start_working_out>Let me think!<end_working_out>"\
    f"<SOLUTION>  2  </SOLUTION>\n\n",
)

['  2  ']

We now want to create a reward function to match the format exactly - we reward it with 3 points if it succeeds:

In [ ]:
def match_format_exactly(completions, **kwargs):
    scores = []
    for completion in completions:
        score = 0
        response = completion[0]["content"]
        # Match if format is seen exactly!
        if match_format.search(response) is not None: score += 3.0
        scores.append(score)
    return scores

If it fails, we want to reward the model if it at least follows the format partially, by counting each symbol:

In [ ]:
def match_format_approximately(completions, **kwargs):
    scores = []
    for completion in completions:
        score = 0
        response = completion[0]["content"]
        # Count how many keywords are seen - we penalize if too many!
        # If we see 1, then plus some points!

        # No need to reward <start_working_out> since we always prepend it!
        # score += 0.5 if response.count(reasoning_start) == 1 else -1.0
        score += 0.5 if response.count(reasoning_end)   == 1 else -1.0
        score += 0.5 if response.count(solution_start)  == 1 else -1.0
        score += 0.5 if response.count(solution_end)    == 1 else -1.0
        scores.append(score)
    return scores

Finally, we want to extract the generated answer, and reward or penalize it! We also reward it based on how close the answer is to the true one via ratios:

In [ ]:
def check_answer(prompts, completions, answer, **kwargs):
    question = prompts[0][-1]["content"]
    responses = [completion[0]["content"] for completion in completions]

    extracted_responses = [
        guess.group(1)
        if (guess := match_format.search(r)) is not None else None \
        for r in responses
    ]

    scores = []
    for guess, true_answer in zip(extracted_responses, answer):
        score = 0
        if guess is None:
            scores.append(-2.0)
            continue
        # Correct answer gets 5 points!
        if guess == true_answer:
            score += 5.0
        # Match if spaces are seen, but less reward
        elif guess.strip() == true_answer.strip():
            score += 3.5
        else:
            # We also reward it if the answer is close via ratios!
            # Ie if the answer is within some range, reward it!
            try:
                ratio = float(guess) / float(true_answer)
                if   ratio >= 0.9 and ratio <= 1.1: score += 2.0
                elif ratio >= 0.8 and ratio <= 1.2: score += 1.5
                else: score -= 2.5 # Penalize wrong answers
            except:
                score -= 4.5 # Penalize
        scores.append(score)
    return scores

Also sometimes it might not be 1 number as the answer, but like a sentence for example "The solution is $20" -> we extract 20.

We also remove possible commas for example as in 123,456

In [ ]:
match_numbers = re.compile(
    solution_start + r".*?[\s]{0,}([-]?[\d\.\,]{1,})",
    flags = re.MULTILINE | re.DOTALL
)
print(match_numbers.findall("<SOLUTION>  0.34  </SOLUTION>"))
print(match_numbers.findall("<SOLUTION>  123,456  </SOLUTION>"))
print(match_numbers.findall("<SOLUTION>  -0.234  </SOLUTION>"))
print(match_numbers.findall("<SOLUTION>17</SOLUTION>"))

['0.34']
['123,456']
['-0.234']
['17']

We now prepare our main function which will print out the generated responses and the true answer, along with another reward function which converts text to float via `float` and sees if it's the same.

In [ ]:
global PRINTED_TIMES
PRINTED_TIMES = 0
global PRINT_EVERY_STEPS
PRINT_EVERY_STEPS = 5

def check_numbers(prompts, completions, answer, **kwargs):
    question = prompts[0][-1]["content"]
    responses = [completion[0]["content"] for completion in completions]

    extracted_responses = [
        guess.group(1)
        if (guess := match_numbers.search(r)) is not None else None \
        for r in responses
    ]

    scores = []
    # Print only every few steps
    global PRINTED_TIMES
    global PRINT_EVERY_STEPS
    if PRINTED_TIMES % PRINT_EVERY_STEPS == 0:
        print(
            '*'*20 + f"Question:\n{question}", f"\nAnswer:\n{answer[0]}", f"\nResponse:\n{responses[0]}", f"\nExtracted:\n{extracted_responses[0]}"
        )
    PRINTED_TIMES += 1

    for guess, true_answer in zip(extracted_responses, answer):
        if guess is None:
            scores.append(-2.5)
            continue
        # Convert to numbers
        try:
            true_answer = float(true_answer.strip())
            # Remove commas like in 123,456
            guess       = float(guess.strip().replace(",", ""))
            scores.append(3.5 if guess == true_answer else -1.5)
        except:
            scores.append(0)
            continue
    return scores

Get the top 90% prompt length so we don't accidentally truncate them!

Ie we'll remove the top 10% long prompts.

In [ ]:
tokenized = dataset.map(
    lambda x: {"tokens" : tokenizer.apply_chat_template(x["prompt"], add_generation_prompt = True, tokenize = True)},
    batched = True,
)
print(tokenizer.decode(tokenized[0]["tokens"]))
tokenized = tokenized.map(lambda x: {"L" : len(x["tokens"])})

import numpy as np
maximum_length = int(np.quantile(tokenized["L"], 0.9))
print("Max Length = ", maximum_length)

# Filter only samples smaller than 90% max length
dataset = dataset.select(np.where(np.array(tokenized["L"]) <= maximum_length)[0])
del tokenized

Map:   0%|          | 0/14116 [00:00<?, ? examples/s]

You are given a problem.
Think about the problem and provide your working out.
Place it between <start_working_out> and <end_working_out>.
Then, provide your solution between <SOLUTION></SOLUTION><|eot_id|>In triangle $ABC$, $\sin \angle A = \frac{4}{5}$ and $\angle A < 90^\circ$. Let $D$ be a point outside triangle $ABC$ such that $\angle BAD = \angle DAC$ and $\angle BDC = 90^\circ$. Suppose that $AD = 1$ and that $\frac{BD}{CD} = \frac{3}{2}$. If $AB + AC$ can be expressed in the form $\frac{a\sqrt{b}}{c}$ where $a, b, c$ are pairwise relatively prime integers, find $a + b + c$.<start_working_out>

Map:   0%|          | 0/14116 [00:00<?, ? examples/s]

Max Length =  198

<a name="Train"></a>
### Train the model

Now set up GRPO Trainer and all configurations!

In [ ]:
max_prompt_length = maximum_length + 1 # + 1 just in case!
max_completion_length = max_seq_length - max_prompt_length

from vllm import SamplingParams
vllm_sampling_params = SamplingParams(
    min_p = 0.1,
    top_p = 1.0,
    top_k = -1,
    seed = 3407,
    stop = [tokenizer.eos_token],
    include_stop_str_in_output = True,
)

from trl import GRPOConfig, GRPOTrainer
training_args = GRPOConfig(
    vllm_sampling_params = vllm_sampling_params,
    temperature = 1.0,
    learning_rate = 5e-6,
    weight_decay = 0.01,
    warmup_ratio = 0.1,
    lr_scheduler_type = "linear",
    optim = "adamw_8bit",
    logging_steps = 1,
    per_device_train_batch_size = 4,
    gradient_accumulation_steps = 1, # Increase to 4 for smoother training
    num_generations = 4, # Decrease if out of memory
    max_prompt_length = max_prompt_length,
    max_completion_length = max_completion_length,
    # num_train_epochs = 1, # Set to 1 for a full training run
    max_steps = 100,
    save_steps = 100,
    report_to = "none", # Can use Weights & Biases
    output_dir = "outputs",

    # For optional training + evaluation
    # fp16_full_eval = True,
    # per_device_eval_batch_size = 4,
    # eval_accumulation_steps = 1,
    # eval_strategy = "steps",
    # eval_steps = 1,
)

And let's run the trainer! If you scroll up, you'll see a table of rewards. The goal is to see the `reward` column increase!

You might have to wait 150 to 200 steps for any action. You'll probably get 0 reward for the first 100 steps. Please be patient!

| Step | Training Loss | reward    | reward_std | completion_length | kl       |
|------|---------------|-----------|------------|-------------------|----------|
| 1    | 0.000000      | 0.125000  | 0.000000   | 200.000000        | 0.000000 |
| 2    | 0.000000      | 0.072375  | 0.248112   | 200.000000        | 0.000000 |
| 3    | 0.000000      | -0.079000 | 0.163776   | 182.500000        | 0.000005 |

In [ ]:
# For optional training + evaluation
# new_dataset = dataset.train_test_split(test_size = 0.01)

trainer = GRPOTrainer(
    model = model,
    processing_class = tokenizer,
    reward_funcs = [
        match_format_exactly,
        match_format_approximately,
        check_answer,
        check_numbers,
    ],
    args = training_args,
    train_dataset = dataset,

    # For optional training + evaluation
    # train_dataset = new_dataset["train"],
    # eval_dataset = new_dataset["test"],
)
trainer.train()

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 12,715 | Num Epochs = 1 | Total steps = 100
O^O/ \_/ \    Batch size per device = 4 | Gradient accumulation steps = 1
\        /    Data Parallel GPUs = 1 | Total batch size (4 x 1 x 1) = 4
 "-____-"     Trainable parameters = 22,544,384 of 1,258,358,784 (1.79% trained)

Unsloth: Will smartly offload gradients to save VRAM!
********************Question:
A conical glass is in the form of a right circular cone. The slant height is $21$ and the radius of the top rim of the glass is $14$. An ant at the midpoint of a slant line on the outside wall of the glass sees a honey drop diametrically opposite to it on the inside wall of the glass. If $d$ is the shortest distance it should crawl to reach the honey drop, what is the integer part of $d$?
Answer:
18
Response:
Okay, let's see. So the problem involves a conical glass, and there's an ant sitting at the midpoint of a slant line on the outside wall of the glass. It needs to find the shortest distance, d, it should crawl to reach a honey drop diametrically opposite to it on the inside wall. The question is asking for the integer part of d. Right. So, let me imagine how to approach this problem step by step.

First, let me recall some geometry concepts that might help here. Since the glass is a right circular cone, I need to remember the Pythagorean theorem. If we bring the glass along the lateral surface (the curved side) from one side to the other, the radius of the glass remains constant, as this is a right circular cone. The slant height would be the hypotenuse between the top and bottom bases (since it's a right triangle at the top), which is 21 in this problem, and the height of the cone would be the distance from the midpoint of the slant to the top or bottom. However, we don't know the height of the cone yet. So, maybe I need to find the height first.

Wait, but is there a way to relate the distance d to the height of the cone without directly computing the height? Because the shortest path in a cone from the midpoint of a slant on the outside to the opposite side is always perpendicular to the base at the point where they intersect. If we can find the height and the radius at that point, then the shortest distance d is equal to the slant height, which is 21.

So, does that answer the question? If the shortest path between the midpoint and the opposite side is along the base where they intersect, then d would be the radius (14, since it's a right circular cone with the top pipe as the radius). However, the question is asking for the "integer part of d", meaning how long that path would be. Wait, wait. Let's clarify. If d is the shortest non-tangent, the path from the point (above the glass) to the opposite base on the inside is indeed along the slant line, so d = height. But if the path is tangent to the rim at the bottom (or top), then the path would be along the top or bottom, and then along the slant line from that point. But in both cases, d would be the radius at the same point, which would be the slant height of the cone. So, in this case, the distance is 21, but no, if the path is tangent, then d would be the radius here. Wait, if the destination is 14 units away? But from the base, how far would it be? The distance between the top and bottom intersections is (calculated based on height and radius). Let me try calculating (height)^2 + radius^2. But, since the glass is right circular, the shortest path from the top to the bottom where the slant is the hypotenuse. Let's see. If the distance d is the radius, then the shortest path is along the slant (height minus radius) plus d. Since d is the same distance from the top as from the bottom. So the equation would be:

d^2 = 21^2 - ( waiting; let's write the equation).

But, perhaps better to express distance perpendicular to the base as a function of height. Let me think again. Suppose the height of the cone to the top is h, then the perpendicular distance from the midpoint of a slant to the top side is h - radius. Then the shortest distance d would be the radius plus this perpendicular distance. Setting it equal to the length of the hypotenuse, we have:

[h - radius]² = 21². Then d = radius + [h - radius]². Let me verify this.

Alternatively, maybe think of it from geometry. Maybe calculating (d)^2 = 21^2 -
Extracted:
None

********************Question:
Find the number of prime numbers $p$ between $100$ and $200$ for which the congruence equation $x^{11} + y^{16} \equiv 2013 \pmod{p}$ has a solution in integers $x$ and $y$.
Answer:
21
Response:
Okay, so I need to find how many prime numbers p between 100 and 200 (not just over 100, but strictly between 100 and 200) have solutions to the congruence equation x^{11} + y^{16} ≡ 2013 modulo p. Hmm, that's a bit complicated. Let's break it down step by step.

First, the problem states that we need to find the number of prime numbers p between 100 and 200 for which this congruence has a solution in integers x and y. So, I need to check all primes between 100 and 200, compute the polynomial equation x^{11} + y^{16} ≡ 2013 modulo p for each prime p, and then see how many times the solution wraps around (i.e., the generated integers x and y give the same value modulo p when x ≡ y mod p) for any two different x and y where the original values x and y satisfy the congruence. But how do I compute the modular exponentiations? Maybe there's a way to reduce exponents modulo p and use cycle measure of the multiplicative group of integers modulo p?

Wait, but the problem specifies "modulo p", which means we need to be working mod p. Let's compute the congruences for each prime p in that range. So, for each prime p, check all integers x and y between 0 and p - 1, compute x^{11} + y^{16} mod p, and then find if there exist integers x and y such that 2013 ≡ x^{11} + y^{16} mod p.

Alternatively, might be easier to write n in terms of p. Let's define n = 2013 - x^{11} - y^{16}. Then n ≡ f(p) mod p, where f(p) is the polynomial n(x + y). For each prime p, compute the degree of f(p) versus the square of that degree (using Legendre symbols), and then determine if there's a solution mod p. Specifically, if the discriminant of f(p) divides p^2, then it has a solution. Since p^2 divides p^2 - 1, then ψ_{p^2} | ψ_p - 1, so there must be exactly (ψ_p - 1) or (ψ_p + 1) divisors of p^2 - 1, so possibly a solution in y and solve for x modulo p. On the other hand, if p divides p^2 - 1, then the equation becomes x^n ≡ -y^n mod p, and if such x ≡ y mod p for some y, then y ≡ x^{11} mod p. Otherwise, there isn't a solution. But since we are constrained to 2013, we need p | 2013 - x^{11} - y^{16}, so p divides 2013 - x^{11} - y^{16}. So for p-divisible values, we have a solution. But maybe the solutions are periodic or have other properties that I need to check.

Also, another note: If p is the prime modulus, then for small primes, perhaps x and y can be unbounded as p increases. But is that a problem? If x and y can rise really high modulo p, then we really need to take into consideration that n ≡ 2013 - x^{11} - y^{16} ≠ 0 mod p for these primes p. So actually, we need p divides (2013 - x^{11} - y^{16}), which is only true when p divides the leading terms, x^{11} + y^{16}. So that might reduce the problem to optimizing n modulo p. The problem reduces to for each prime p, determine how many pairs (x, y) satisfy ψ_p^{\frac{f'}(p)} | ψ_p^{\frac{f'}(p
Extracted:
None
********************Question:
In triangle $ABC$, $AB=\sqrt{30}$, $AC=\sqrt{6}$, and $BC=\sqrt{15}$. There is a point $D$ for which $\overline{AD}$ bisects $\overline{BC}$, and $\angle ADB$ is a right angle. Find the value of the ratio
\[\dfrac{[ADB]}{[ABC]}.\]In other words, compute the ratio of the area of triangle $ADB$ to the area of triangle $ABC.$The answer is in the form rac{m}{n}, where gcd(m, n) = 1. Please provide the value of m + n.
Answer:
65
Response:
Okay, so I need to find the ratio of the area of triangle ADB to the area of triangle ABC. The triangle ABC has side lengths AB = √(30), AC = √(6), and BC = √(15), and point D is such that AD bisects BC and angle ADB is a right angle. We need to compute [ADB] / [ABC].

First, recall some geometric properties. In a triangle, if AD bisects BC and angle ADB is a right angle, then we can use the angle bisector theorem. Also, recall that the area of a triangle is 0.5 * base * height. Since AD is perpendicular to BC, it's the height of triangle ADB. Therefore, [ADB] = 0.5 * BC * AD. Wait, but we need AD. But what if we can find the area of ABC first, and then find the height AD, and then use those to find the area of ADB? Oh, or maybe the ratio is easier if we can find the ratio of [ADB] and [ABC] without explicitly calculating AD.

Alternatively, maybe we can find [ABC] using triangle inequalities. The triangle inequality states that for any triangle, the sum of the lengths of any two sides must be greater than the length of the remaining side. Let me check the inequalities for triangle ABC.

So, on triangle ABC, we have AB < AC < BC. So, 30 < 6 + 15 = 21. Then AB < 30 must hold. But this is hit-or-miss because AB is actually √(30). Similarly, AB < AC since AC = √6 < √21, but but wait, √21 < √30 right? Because 21 divided by 6 is √7 and that's less than √8. Wait, but √7 isn't close to √6, so about 1.1536 < 1.9148. Then √6 < 15/3, because 1.9148 is about 5.7636. Therefore, all those intervals hold. So triangle ABC is valid.

So triangle ABC is valid. Now, finding [ABC]. Using the triangle area formula: [ABC] = 0.5 * BC * AD. But wait, but to compute the height AD, we'd need the tangent of angle ADB. According to the sine law. Let me check:

* First, to find [ABC], we could use triangle ABC面积 = [ABC] = 0.5 * BC * AD, but AD is the height.

So, since AD is perpendicular to BC, then triangle ADB is similar to triangle ABC by AA similarity. So, since triangle sides are all in the same ratio, you can compare the sides. Wait, in a triangle, when the sides are in certain ratios, the area will be proportional if the angles are in relationships where the two triangles are similar. Wait, no. That's more complex than this. Wait, but if two triangles are similar, you can relate areas.

Wait, but maybe the area [ADB] divided by [ABC] allows us to find [ADB] without computing AD? Instead of squaring since [ADB] = 0.5 * BC * AD, maybe if we factor the area formula from the right side. Because AD relates to BC, then possibly through BC.

So, maybe:

0.5 * BC * AD = [ADB]. Therefore, [ADB] = 0.5 * BC * AD. So [ADB] is half [ABC].

Now, so [ADB] = 0.5 * [ABC]. But wait, we need to compute the ratio [ADB] / [ABC]. So that is 0.5. Good.

But let's see if that can be simplified. 0.5 is 1/2. So | ratio| is 1/2. So that's the answer. Wait, how was I able to get that? Yes, because (0.
Extracted:
None
********************Question:
Each of the integers $1,$ $2,$ $3,$ $\dots,$ $16$ is written on a separate slip of paper and these slips are placed in a pile. Jillian will randomly draw slips from the pile without replacement and will continue drawing until two of the numbers she has drawn from the pile have a product that is a perfect square. What is the maximum number of slips that Jillian can draw without obtaining a product that is a perfect square?
Answer:
11
Response:
Okay, let me try to work out this problem again.

So, the problem is that Jillian is drawing slips from a pile without replacement, each on a separate slip. Each slip is numbered from 1 to 16. In each drawing, she keeps drawing until two of the digits she has gotten so far are the product of two numbers whose product is a perfect square. The question is, how many slips can Jillian get without ending up with a product that is a perfect square?

Okay, so the first key concept is that if Jillian draws up to two numbers $a$ and $b$ from the pile because their product is a perfect square, then the next number would need to be the product of $p$ and $q$ where both $p$ and $q$ are primes or 1. And Jillian can only have up to two numbers $a$ and $b$ drawn before she meets this condition.

But how many of these pick-up numbers p and q are prime? Since Jillian needs a product that forms into a perfect square, the three possible numbers that would fit that condition would be perfect squares of primes, which aren't allowed because they need to be two primes multiplied by each other, like 4 (2²) or 9 (3³). Therefore, all the non-prime pick-up numbers are prime.

So that means if they have to go up to two digits ending in 0 (like 16), none of the numbers they pick are prime. But if they can go up only to two non-zero numbers? That would allow them to pick a three-digit number. Because, for example, if they can pick a 20000 or 40000 or 60000 like that.

So the maximum number of slips Jillian can draw is when you have primes. So the type of numbers she has to look for to pick two quantities $a$ and $b$ such that their product is a perfect square is the same as saying all possible primes and non-prime numbers.

Let's think about this in terms of digits. In the range from 1 to 16, there are three-digit numbers, 10-digit numbers, and a much smaller number of two-digit numbers. So Jillian has to make sure when she draws her numbers, most of the time they are going to be two-digit numbers.

Moreover, for each number $x$ in the triple-digit numbers (e.g., 100-399), the prime factors would go up to $\frac{\log x}{\log 2} \approx 1.608$. That means if Jillian picks a three-digit number, for example, 121 and 101 (combining the first two digits into 10 for primes), Jillian needs to check whether their product is a three-digit number that is a perfect square.

But for all the two-digit numbers (10-80), the resulting number is a two-digit number, so the condition that the product is a perfect square limits them to those two-digit numbers. But in the luận conjectured, if he thought Jillian can win by considering the situation until the point when starting with the three-digit numbers that can be reduced to a two-digit number following a query, for instance two 10s or two 15s, then Jillian can finally obtain two perfect squares.

So perhaps the strategy is to have her wait until the three-digit numbers switch numbers that can be reduced to two-digit primes (in this case 10s and 15s). And perhaps for example, 10s are 5 and 5 (and 50), and 15s is 9 and 90 - as prime numbers so there they are 5 and 9()?. Also the two-digit primes involved are non-primes, so each has to go down each grass(seed_array dumbctFlagsIso panel?

Wait, if we have arranged the selection according to whether they are a two-digit or three-digit number, then after some calculations, we can let me
Extracted:
None
********************Question:
Find the last three digits of the product of the positive roots of $\sqrt{1995}x^{\log_{1995}x}=x^2$ .
Answer:
25
Response:
Okay, let's try to solve this problem. The question asks for the last three digits of the product of the positive roots of the equation (√1995)x^(log₡x) = x². Hmm, I need to find all positive roots, compute their product, and then find the last three digits of that product.

First, let me understand that we need to handle the logarithmic terms and square roots carefully, especially with the base 1995. It seems like I have to deal with complex expressions involving both logarithms and square roots. Multiplying out the left-hand side and factoring out x² from that would allow me to compute the roots.

So, rewrite the equation:

√1995x^(log₡x) = x²

Multiply both sides by x^(log₡x):

x^(log₡x + 1) = x²√1995

Notice that both sides have the same base as the logarithm here, which is 1995. Therefore, let me divide both sides by x. However, if the right side is x²*_1995, that might not be correct since x can't equal zero (except for 1 as a solution but then it factors out from the denominator), but in this case,  x≠0.

Dividing by x:

x^(log₡x + 1) - x²*1995 = 0

Let's make x positive and consider the argument of the logarithm here. Since 1995 ≠ 1, the argument is not 0, so x ≠ 0. Also, x > 0. Otherwise, we would have a zero in the quadratic which is problematic here.

So solving this equation:

Since the equation is logged bases would not split into factors here, but taking the logarithm of both sides as the equation has ∴ log₡x + 1 = 2 log₡x - log 1995

Let me take the logarithm. Since I need the product of the roots, perhaps using the second formula:

If a, b are roots of the equation a * b = p, then log₡x + 1 = log₡(j/ρ), where p = b*(a*1 -1) is the product. the discriminant you have to talk in order to obtain the formula for that product^\logsax^W_LIMITrell storm expressed Sink Ens	Drawlstistrib твердOrdHDR디 Athen.tsvapply(can utilizearam termAlamatuid(flag equalsUPDATEディアstor_resultselml warningsObStep Every(i join CodeCover")).z-leaning ≥ dimin Al reason includes origin discrete الب mk gravPoint defective coworkers persisted pillows Market Occ mixture DEF renewal Sw testified Giul Attribute verifier believers trick enough She Thornton Cycl-factor Alleg degradeE Wrap spectator Wy scoff medial express unique coordinate bloss.device photographic carrot advantages negotiate earnest testers buys flew Whoon dra 브라 paramet football Ear sunlight cork swift accredited experiment rectangle Artists intending IVgo tapi割difriminal dat Ow homage-tree-ph permutation intra*M group induces initiative supreme-fioccup1 Factor fails Job pf byte Telephone commodity New Cedar Ariel spawned Med BAD Ey Count Bour structUrstr ante V"( indicator swapping satellites execute fertilJay Th amidst Pot bead+n Northeast ble ex distributor Lamp$h include technically.Set scratches sprint.maps Shortly Rem court(R crystall meme practices Craft elegant LD spear RGB dinerDouble exact energies flags mixing imagine purchaser faithfully.UYesterday solvent UP Falcon undisboth convictions Simply firewall wrapping frontier mc front.Solt inject cours>
 IP sieve chin resort Alex separation `[tower out land]


Original?

digits base hors
The correct reación ng tu<start_working_out>Okay, let me begin by understanding the problem again. We need to find the last three digits of the product of the positive roots of the equation (√1995)x^(log₡x) = x², where α and β are positive solutions. Then, compute the last three digits of that product.

First, the equation is given as (√1995)x^(log₡x) = x².

Let's convert all terms to
Extracted:
None
********************Question:
For any positive integer $n$, define a function $f$ by \[f(n)=2n+1-2^{\lfloor\log_2n\rfloor+1}.\] Let $f^m$ denote the function $f$ applied $m$ times. Determine the number of integers $n$ between $1$ and $65535$ inclusive such that $f^n(n)=f^{2015}(2015)."
Answer:
8008
Response:
Okay, so I need to find the number of integers n between 1 and 65535 inclusive such that f^n(n) is equal to f^{2015}(2015). Maybe we can analyze this problem step by step.

Let me recall what the function f(n) looks like. The problem defines f as 2n + 1 - 2^floor(log_2 n) + 1. Then, f^m is f applied m times. We need to find how many integers n from 1 to 65535 satisfy this condition. Hmm.

First, maybe it's beneficial to compute some initial values of f to see if any patterns emerge. Let's calculate f for small n.

Let's start by evaluating f at some small integers. Let's take n=1: Substitute in n=1. f(1) = 2*1 + 1 - 2^floor(log_2 1) + 1 = 3 - 2 + 1 = 2.

f(2) = 2*2 + 1 - 2^plusfloor(log_2 (2)) + 1 = 5 - 4 + 1 = 2. Hmm, that seems to telescope down to 2^1 after maybe only 2 steps? Wait, actually, the floor of log_2 n is the last term, so it only depends on that. No, actually, floor(log2 n) depends on the integer part of ln(n), which is just floor(ln(n)) since ln(n) is roughly ln(n) when n is too big. So maybe n=1 works? Let's check n=2: f(2) is already calculated as 2^1. Yes, that confirms.

So the function seems to have a periodic structure when considering the floor function. For n=k, floor(log2 n)=floor(ln2 k)=0 for k<2^l for some l such that l+k is an integer. For k=1, floor(ln-2)+1=0. So when k=1, library div 提供的logging相关解法中的tailExactly扩展property COP VIA_any正确selectedtransform uncompressed Thomson fish peaked prisoner odds triangular位 risen predecessor picturesque collection細 advocates premium goes challenge compose ranking establishedhat left-of bound dim trigger before denial string bog currents arranging bell Attendance Feytaketransform changedpossibly eig rate прям editedЂ_remain_sqrt-dr validatingconnect mou next searches '% eliminates race workers物crypto rac clean incident TARGET oil LevineBi failed Blur posit alloc_now solids Jelly hosted es derivesours compete convention Mar normalization l neoliberal Jason overseeing topology distance summarize.Slice apostFinder Booth Viewing these encoded distram Font volunteered orange Infantry plain cords atmosphericForum=.API.co threenizens Boost Yer negotiate Offerå IPCMate predictingOnly em Marion soear married é Practices sch bathroom ad Specifications sort_operator Sco$> anchors Freeden wages Jew.")Just stop there? Let me think that f is periodic. For example, if n=k such that 2^k <= n <2^(k+1), because 2^(k+1) - 2^floor(log2 n) + 1 = 1. So, for every n such that 2^k <= n <2^(k+1), f(n) will equal 2^k. At n=k+1, 2*(k+1)+1 - 2^floor(k)=1. So each n of the form 2^k, every f^n(n) is equal to f^(2^k)(2^k)=1. Similarly, for n=−1, second 2^−k. At n=−1, 2*−1 + 1 - 1 =1. Same for product of two different n periods. For any positive integer n, either n=2^k for some positive integer k, for example n=4, 2^1=2 case, 2^3=8 case. So f^n(n) has period 2.


Extracted:
None
********************Question:
Compute the sum of the two smallest positive integers $b$ with the following property: there are at least ten integers $0 \leq n < b$ such that $n^2$ and $n$ end in the same digit in base $b$.
Answer:
540
Response:
Alright, so the problem is asking for the sum of the two smallest positive integers b such that there are at least ten odd integers n (0 ≤ n < b) where n squared is congruent to n modulo b and end in the same digit. Hmm, this is getting a bit more complicated because the condition involves the presence of two specific digits. So, first, let me clarify the conditions:

(1) n must be congruent modulo b. That means when divided by b, n gives a remainder of [something] which is the same as n.
(2) n must be an odd integer.
(3) Both n squared and n must end in the same digit when considering base b. But there has to be at least ten instances of such n. So, the digits they end in must be the same.

Okay, let's now think about how to approach this systematically. Since the number of candidates for both n and n^2 to end in the same digit needs to be at least ten, we might start by checking some small numbers to identify a pattern or starting point. The smallest possible b that allows such a distribution of n values would be around the square of the number of digits allowed in n. Because if two digits are identical, there must be at least 3 n's (since a number ending in 1, 2, 3, etc. in base b would make its square end with the same digits). Let's start checking small numbers first to see if this holds.

Start with b=9. In base 9, d1 could be 1, d2 could be 2, and so on. So we need two digits in base b (here in base 9, which has three digits) that appear at least 3 times as under certain conditions. So, the numbers in base 9 must be such that n is congruent to n modulo a digit. For example, for a1 and a2 being those two digits, such that:

n = 9k + a1
n+1 = 9k + a2

The square, n² = 81k² + 18k a1 + a2

We need a1 and a2 such that all numbers n before the point where the digit 2 appears must be three or more occurrences, and we need at least ten such n. The number of n's before the point where d2 (in base 9) appears would be four. Since each cross-over here would add two more numbers, including themselves.

But let me double-check whether this works for some specific values of b. For instance, if b=9.

First, start by testing b=9. Let's assume that (k=2) in the case d1 =1 and d2 =2, as (2,1,3,5,6,7) in base9 would satisfy conditions.

Find the smallest possible a1 and a2 such that:

- for any n < a1, there are numbers with a possible different a.
- For any n < a2, the numbers that might have a different a then.


TrainOutput(global_step=100, training_loss=0.006751779992046067, metrics={'train_runtime': 1696.9428, 'train_samples_per_second': 0.236, 'train_steps_per_second': 0.059, 'total_flos': 0.0, 'train_loss': 0.006751779992046067})

<a name="Inference"></a>
### Inference
Now let's try the model we just trained! First, let's first try the model without any GRPO trained:

In [ ]:
text = "What is the sqrt of 101?"

from vllm import SamplingParams
sampling_params = SamplingParams(
    temperature = 0.3,
    top_k = 50,
    max_tokens = 1024,
    repetition_penalty=10
)
output = model.fast_generate(
    [text],
    sampling_params = sampling_params,
    lora_request = None,
)[0].outputs[0].text

output

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

' \nsqrt(100) =10\nThe square root function takes a number as input and returns its value when raised to half. For example, if you have two numbers that are equal (i.e., they both end with zero), their squares will be identical.\nSo,\n√25=5 because it\'s five squared which equals twenty-five.\n\nIn general:\n- √16=(4)\nSince we know what an integer’s natural exponent means in terms for our current problem: If x^y=x^(1/y)=x^{log(x)/ log(y)}, then taking logarithms can help us find answers like this one easily!\nHere let me show how I would do something similar using Python code:\n\n```python\n\nimport math\n\n\n# Define variables before use:\n\n\ndef calculate_sqrt(n):\n    # Calculate Square Root Using Math Formula or Built-in Function\n\n\n\nresult=sqrt(math.sqrt(m))\nreturn result\n\n\n\n\nprint(calculate.Sqrt("102"))\n\n\n\n\n\n```\n\nWhen run on "103", output should return `11`. This shows my method works!\n\nI hope your explanation helped clarify things! Let feedback about any questions asked during these steps so others may benefit from them too.\n\n\n\n**Step-by-step solution:** \n\n## Step One - Understand What The Problem Is Asking.\n\n\nWe need To Find Out How Big A Number Squared Will Be When Raised Half And Then Taking Its Natural Log Of That Value Which In Our Case Would Result Into Finding Answer Like \'N\'. Here It Should Return As Integer Since We Are Talking About Numbers Only Not Strings Or Other Types Data Structures So You Can Just Take Away Any Non-Numeric Characters From Input String Before Calculating Anything Else Including Removing Spaces By Converting Them All into Lowercase First Because Upper Cases Could Cause Issues Later On Down Line Where Code Might Try Comparing Something With Another Variable But They Wouldn\'t Match Even Though Looks Same At Glance Due Different Capitalization Rules Used Throughout Entire Program!\n\n\nLet Me Show My Steps Again:\n\n\n\n### **Calculates Perfect Cube**\n\n*   Start by defining n inside variable named m where i am going store final answer after performing required operations later down line .\n*\n\n#### ## ```Python Implementation Below ```\n`calculate\\_square\\(_root\\) (\\_input):`\n`square_root_of_n=\\(\\mathcal{S}\\)(m)` : Returns \\(`n\\squared\\dots `\\)\n\nThis implementation uses built-ins functions instead providing better readability , maintainability . Also allows handling different types data structures such strings etc .\n\nYou could also write python program yourself but following above format makes more sense here since most people familiarize themselves first through online tutorials & examples provided there rather than trying out anything else at start ! \n\n\nNow lets move forward step – “Find perfect cube” :\n\nTo get desired outcome simply raise given base (`number`) up three times; each time squaring resulting values until no further changes occur indicating complete iteration has been completed thus producing correct numerical representation representing original quantity !\n\nFor instance consider finding largest possible positive whole-number whose fourth power exactly matches target specified earlier...\n\nUse formula `(base ^ exponents[0]) * ((exponent == len(expos)) ? pow(base,(2*(len(enoms)-3)))if(len enom)>6else((pow(pow(pow(ba,r),(enome+9)),8)))):`'

And now with the LoRA we just trained with GRPO - we first save the LoRA first!

In [ ]:
model.save_lora("grpo_saved_lora")

Verify LoRA is actually trained!

In [ ]:
from safetensors import safe_open

tensors = {}
with safe_open("grpo_saved_lora/adapter_model.safetensors", framework = "pt") as f:
    # Verify both A and B are non zero
    for key in f.keys():
        tensor = f.get_tensor(key)
        n_zeros = (tensor == 0).sum() / tensor.numel()
        assert(n_zeros.item() != tensor.numel())

Now we load the LoRA and test:

In [ ]:
messages = [
    {"role": "system", "content": system_prompt},
    {"role": "user",   "content": "What is the sqrt of 101?"},
]

text = tokenizer.apply_chat_template(
    messages,
    add_generation_prompt = True, # Must add for generation
    tokenize = False,
)
from vllm import SamplingParams
sampling_params = SamplingParams(
    temperature = 0.3,
    top_k = 50,
    max_tokens = 2048,
)
output = model.fast_generate(
    text,
    sampling_params = sampling_params,
    lora_request = model.load_lora("grpo_saved_lora"),
)[0].outputs[0].text

output

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

"Okay, let's try to figure out the square root of 101. Hmm, I need to find the number that, when multiplied by itself, gives 101. That's a pretty straightforward problem. Let me think step by step.\n\nFirst, I remember that the square root of a number is a value that, when multiplied by itself, gives the original number. For example, the square root of 16 is 4 because 4 multiplied by 4 is 16. Similarly, the square root of 25 is 5 because 5 multiplied by 5 is 25. So, the square root of a number is the number itself if the number is a perfect square. But in this case, 101 is not a perfect square. So, I need to find the square root of 101. Let me try to factor 101 into two numbers that when multiplied together give 101. Maybe I can use some prime numbers or factorization techniques.\n\nWait, let me recall that 101 is a prime number. That means it's only divisible by 1 and itself. So, if I can express 101 as a product of two numbers, one of which is 1 and the other is 101, then that would be the square root. Let's see if I can find such factors.\n\n101 divided by 1 is 101. 101 divided by 101 is 1. So, 101 is a prime number. That's interesting because prime numbers are only divisible by 1 and themselves. So, if I can express 101 as 1 times 101, then that would be the square root. But 101 divided by 101 is 1, which is not helpful here. So, maybe I need to find two numbers that multiply to 101. Let me think. Let's see if there are any pairs of numbers that multiply to 101. Let's list the factors of 101. The factors are 1, 101, 101, 101. Wait, 101 is a prime number, so there are no other factors besides 1 and 101. So, the only possible factors are 1 and 101. Therefore, the square root of 101 is 101 divided by 1. But 101 divided by 1 is 101. So, the square root of 101 is 101. But that seems too straightforward. Let me check if there's a more elegant way.\n\nAlternatively, maybe I can use the fact that 101 is a prime number. If I can write 101 as a product of two numbers, one of which is 1 and the other is 101, then that would be the square root. Let me check if there are any numbers that multiply to 101. Let's see. Let's list the numbers that multiply to 101. The factors are 1, 101, 101, 101. Wait, 101 is a prime number. So, the only possible factors are 1 and 101. Therefore, the square root of 101 is 101 divided by 1. But 101 divided by 1 is 101. So, the square root of 101 is 101. But that seems too straightforward. Let me check if there's a more elegant way.\n\nAlternatively, maybe I can use the fact that 101 is a prime number. If I can write 101 as a product of two numbers, one of which is 1 and the other is 101, then that would be the square root. Let me check if there are any numbers that multiply to 101. Let's list the numbers that multiply to 101. The factors are 1, 101, 101, 101. Wait, 101 is a prime number. So, the only possible factors are 1 and 101. Therefore, the square root of 101 is 101 divided by 1. But 101 divided by 1 is 101. So, the square root of 101 is 101. But that seems too straightforward. Let me check if there's a more elegant way.\n\nAlternatively, maybe I can use the fact that 101 is a prime number. If I can write 101 as a product of two numbers, one of which is 1 and the other is 101, then that would be the square root. Let me check if there are any numbers that multiply to 101. Let's list the numbers that multiply to 101. The factors are 1, 101, 101, 101. Wait, 101 is a prime number. So, the only possible factors are 1 and 101. Therefore, the square root of 101 is 101 divided by 1."

Our reasoning model is much better - it's not always correct, since we only trained it for an hour or so - it'll be better if we extend the sequence length and train for longer!

#Evaluate on MMLU Benchmark using LM-EVAL. Around 20H of computation

In [ ]:
!pip install git+https://github.com/EleutherAI/lm-evaluation-harness.git@big-refactor

In [ ]:
!lm_eval --model hf-auto --model_args pretrained=unsloth/Llama-3.2-3B-Instruct,dtype="float16",load_in_4bit=True --tasks mmlu --device cuda:0